blueprint:
  name: Adaptívne tienenie - viac miestností (zdieľaný svetelný senzor)
  description: >
    Automatické ovládanie roliet pre viacero miestností na základe jedného senzora osvetlenia.
    Zohľadňuje otvorené okná, úroveň osvetlenia, čas a západ slnka. Odosiela notifikácie pri otvorenom okne.

  domain: automation
  input:
    lux_sensor:
      name: Senzor osvetlenia (spoločný)
      description: Vyberte senzor osvetlenia, ktorý bude monitorovať úroveň svetla
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    morning_trigger_time:
      name: Ranný čas spustenia
      description: Čas, kedy sa začne automatické ovládanie ráno
      default: "07:30:00"
      selector:
        time: {}

    notification_services:
      name: Notifikačné služby
      description: >
        Zadajte názvy notifikačných služieb (napr. notify.mobile_app_iphone_jan).
        Môžete zadať viacero služieb, každú na nový riadok.
      default: []
      selector:
        text:
          multiple: true

    room_config:
      name: Konfigurácia miestností
      description: >
        Pre každú miestnosť vyberte roletu a voliteľne aj senzor okna.
        Ak nie je senzor okna vybraný, roleta sa bude ovládať bez ohľadu na stav okna.
      selector:
        object: {}

initial_state: true

trigger:
  - platform: time
    at: !input morning_trigger_time

  - platform: numeric_state
    entity_id: !input lux_sensor
    below: 600
    for:
      minutes: 5

  - platform: numeric_state
    entity_id: !input lux_sensor
    above: 800
    for:
      minutes: 2

  - platform: sun
    event: sunset
    offset: "-00:30:00"

condition:
  - condition: time
    after: !input morning_trigger_time
  - condition: sun
    before: sunset

action:
  - variables:
      lux_sensor_id: !input lux_sensor
      lux: "{{ states(lux_sensor_id) | float(0) }}"
      rooms: !input room_config
      open_windows: []
      after_sunset: "{{ state_attr('sun.sun', 'elevation') | float(1) < 0 }}"
      notification_services: !input notification_services
      is_bright: "{{ lux > 800 }}"
      is_dark: "{{ lux < 600 }}"
      is_daytime: "{{ not after_sunset }}"

  - service: logbook.log
    data:
      name: "Adaptívne tienenie"
      message: >-
        Debug: lux={{ lux }} lux, is_daytime={{ is_daytime }}, is_bright={{ is_bright }}, 
        is_dark={{ is_dark }}, after_sunset={{ after_sunset }}

  - repeat:
      for_each: "{{ rooms }}"
      sequence:
        - variables:
            name: "{{ repeat.item.name }}"
            window_sensor: "{{ repeat.item.window_sensor | default('') }}"
            cover: "{{ repeat.item.cover }}"
            sensor_id: "{{ window_sensor if window_sensor != '' else 'žiadny senzor' }}"

        - choose:
            - alias: "Rozjasnenie - otvorenie"
              conditions:
                - condition: template
                  value_template: "{{ is_daytime and is_bright }}"
              sequence:
                - service: logbook.log
                  data:
                    name: "Adaptívne tienenie"
                    message: >-
                      Rozhodnutie: Otvorenie rolety v miestnosti {{ name }}
                      - Miestnosť: {{ name }}
                      - Roleta: {{ cover }}
                      - Senzor okna: {{ sensor_id }}
                      - Osvetlenie: {{ lux }} lux
                      - Stav okna: {{ 'otvorené' if window_sensor != '' and is_state(window_sensor, 'on') else 'zatvorené' if window_sensor != '' else 'žiadny senzor' }}
                      - Príznaky: is_daytime={{ is_daytime }}, is_bright={{ is_bright }}, is_dark={{ is_dark }}, after_sunset={{ after_sunset }}
                      - Dôvod: Vysoká úroveň osvetlenia počas dňa
                - condition: template
                  value_template: "{{ not is_state(cover, 'open') }}"
                - service: cover.open_cover
                  target:
                    entity_id: "{{ cover }}"

            - alias: "Stmievanie alebo západ slnka - okamžité zatvorenie"
              conditions:
                - condition: template
                  value_template: "{{ (is_dark and is_daytime) or after_sunset }}"
                - condition: template
                  value_template: "{{ window_sensor == '' or is_state(window_sensor, 'off') }}"
              sequence:
                - service: logbook.log
                  data:
                    name: "Adaptívne tienenie"
                    message: >-
                      Rozhodnutie: Zatvorenie rolety v miestnosti {{ name }}
                      - Miestnosť: {{ name }}
                      - Roleta: {{ cover }}
                      - Senzor okna: {{ sensor_id }}
                      - Osvetlenie: {{ lux }} lux
                      - Stav okna: {{ 'otvorené' if window_sensor != '' and is_state(window_sensor, 'on') else 'zatvorené' if window_sensor != '' else 'žiadny senzor' }}
                      - Príznaky: is_daytime={{ is_daytime }}, is_bright={{ is_bright }}, is_dark={{ is_dark }}, after_sunset={{ after_sunset }}
                      - Dôvod: Nízka úroveň osvetlenia alebo západ slnka, okno zatvorené
                - condition: template
                  value_template: "{{ not is_state(cover, 'closed') }}"
                - delay:
                    seconds: 2
                - service: cover.close_cover
                  target:
                    entity_id: "{{ cover }}"

            - alias: "Stmievanie alebo západ slnka - čakanie na zatvorenie okna"
              conditions:
                - condition: template
                  value_template: "{{ (is_dark and is_daytime) or after_sunset }}"
                - condition: template
                  value_template: "{{ window_sensor != '' and is_state(window_sensor, 'on') }}"
              sequence:
                - service: logbook.log
                  data:
                    name: "Adaptívne tienenie"
                    message: >-
                      Rozhodnutie: Čakanie na zatvorenie okna v miestnosti {{ name }}
                      - Miestnosť: {{ name }}
                      - Roleta: {{ cover }}
                      - Senzor okna: {{ sensor_id }}
                      - Osvetlenie: {{ lux }} lux
                      - Stav okna: otvorené
                      - Príznaky: is_daytime={{ is_daytime }}, is_bright={{ is_bright }}, is_dark={{ is_dark }}, after_sunset={{ after_sunset }}
                      - Dôvod: Nízka úroveň osvetlenia alebo západ slnka, okno otvorené
                - variables:
                    open_windows: "{{ open_windows + [name] }}"
                - repeat:
                    for_each: "{{ notification_services }}"
                    sequence:
                      - service: "{{ repeat.item }}"
                        data:
                          title: "Upozornenie: otvorené okno"
                          message: >-
                            Rolety v miestnosti {{ name }} sa nezatiahnu, pretože je otvorené okno.
                            Po jeho zatvorení sa roleta automaticky zatiahne o 30 sekúnd.
                - wait_template: "{{ is_state(window_sensor, 'off') }}"
                  timeout: "00:05:00"
                  continue_on_timeout: false
                - delay:
                    seconds: 30
                - service: logbook.log
                  data:
                    name: "Adaptívne tienenie"
                    message: >-
                      Rozhodnutie: Zatvorenie rolety po zatvorení okna v miestnosti {{ name }}
                      - Miestnosť: {{ name }}
                      - Roleta: {{ cover }}
                      - Senzor okna: {{ sensor_id }}
                      - Osvetlenie: {{ lux }} lux
                      - Stav okna: zatvorené
                      - Príznaky: is_daytime={{ is_daytime }}, is_bright={{ is_bright }}, is_dark={{ is_dark }}, after_sunset={{ after_sunset }}
                      - Dôvod: Okno bolo zatvorené
                - condition: template
                  value_template: "{{ not is_state(cover, 'closed') }}"
                - service: cover.close_cover
                  target:
                    entity_id: "{{ cover }}"

            - alias: "Žiadna akcia - roleta zostáva nezmenená"
              conditions:
                - condition: template
                  value_template: "{{ not (is_daytime and is_bright) and not ((is_dark and is_daytime) or after_sunset) }}"
              sequence:
                - service: logbook.log
                  data:
                    name: "Adaptívne tienenie"
                    message: >-
                      Rozhodnutie: Žiadna akcia v miestnosti {{ name }}
                      - Miestnosť: {{ name }}
                      - Roleta: {{ cover }}
                      - Senzor okna: {{ sensor_id }}
                      - Osvetlenie: {{ lux }} lux
                      - Stav okna: {{ 'otvorené' if window_sensor != '' and is_state(window_sensor, 'on') else 'zatvorené' if window_sensor != '' else 'žiadny senzor' }}
                      - Príznaky: is_daytime={{ is_daytime }}, is_bright={{ is_bright }}, is_dark={{ is_dark }}, after_sunset={{ after_sunset }}
                      - Dôvod: Osvetlenie mimo rozsahu ({{ lux }} lux) alebo stále noc

  - if:
      - condition: template
        value_template: "{{ open_windows | length > 0 and notification_services | length > 0 }}"
    then:
      - repeat:
          for_each: "{{ notification_services }}"
          sequence:
            - service: "{{ repeat.item }}"
              data:
                title: "Upozornenie: otvorené okná"
                message: >-
                  Vonku sa stmieva a nasledujúce miestnosti majú otvorené okná,
                  preto sa rolety nezatiahli: {{ open_windows | join(', ') }}

mode: single
