blueprint:
  name: Battery Monitor v4
  description: >
    Monitors battery sensors and sends notifications when battery level
    is below threshold. Notifications repeat daily until battery recovers.
    Memory is stored as JSON list in input_text.
  domain: automation

  input:
    battery_sensors:
      name: Battery Sensors
      description: Select battery sensors to monitor
      selector:
        entity:
          multiple: true
          filter:
            - domain: sensor
            - device_class: battery

    threshold:
      name: Battery Threshold (%)
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1

    notification_time:
      name: Notification Time
      default: "08:00:00"
      selector:
        time: {}

    notification_services:
      name: Notification Services
      description: List of notification services (e.g., notify.mobile_app_x), one per line
      default: []
      selector:
        text:
          multiple: true

    use_persistent_fallback:
      name: Use Persistent Fallback
      description: If no notification services provided, create persistent notification in HA
      default: true
      selector:
        boolean: {}

    memory_helper:
      name: Memory Helper
      description: input_text entity where JSON list of currently low batteries is stored
      selector:
        entity:
          domain: input_text

    debug:
      name: Debug Mode
      description: Enable debug notifications for invalid entities
      default: false
      selector:
        boolean: {}

trigger:
  - platform: time
    at: !input notification_time

variables:
  threshold: !input threshold
  sensors: !input battery_sensors
  notify_services: !input notification_services
  use_persistent_fallback: !input use_persistent_fallback
  memory_helper: !input memory_helper
  debug: !input debug

mode: single

action:
  - variables:
      notify_services_filtered: >-
        {% set services = notify_services | default([]) %}
        {{ services | map('string') | map('trim') | reject('equalto', '') | unique | list }}
      memory_list: >-
        {% set raw = states(memory_helper) | string %}
        {% set raw_trimmed = raw | trim %}
        {% if raw_trimmed in ['', 'unknown', 'unavailable', 'none'] %}
          []
        {% elif raw_trimmed | length >= 2 and raw_trimmed[0] == '[' and raw_trimmed[-1] == ']' %}
          {% set parsed = raw_trimmed | from_json %}
          {% if parsed is list %}
            {{ parsed }}
          {% else %}
            []
          {% endif %}
        {% else %}
          []
        {% endif %}
      current_low_entities: []
      current_low_batteries: []
      recovered_batteries: []
      unavailable_memory_entities: []
      invalid_entities: []

  - repeat:
      for_each: "{{ sensors }}"
      sequence:
        - variables:
            ent: "{{ repeat.item }}"
            raw: "{{ states(repeat.item) | string }}"
            norm: "{{ raw | trim | lower | replace(',', '.') | replace('%', '') | replace(' ', '') }}"
            lvl: >-
              {% set v_float = norm | float(default=-1) %}
              {% if v_float < 0 or v_float > 100 %}
                -1
              {% else %}
                {{ v_float }}
              {% endif %}
            display_name: "{{ state_attr(repeat.item, 'friendly_name') or repeat.item }}"
            unit_of_measurement: "{{ state_attr(repeat.item, 'unit_of_measurement') }}"

        - if:
            - condition: template
              value_template: "{{ lvl == -1 }}"
          then:
            - variables:
                invalid_entities: "{{ invalid_entities + [{'ent': ent, 'raw': raw, 'unit': unit_of_measurement}] }}"

        - if:
            - condition: template
              value_template: "{{ lvl >= 0 and lvl <= threshold }}"
          then:
            - variables:
                current_low_entities: "{{ current_low_entities + [ent] }}"
                current_low_batteries: "{{ current_low_batteries + [{'name': display_name, 'lvl': lvl}] }}"

  - repeat:
      for_each: "{{ memory_list }}"
      sequence:
        - variables:
            mem_ent: "{{ repeat.item }}"
            mem_raw: "{{ states(repeat.item) | string }}"
            mem_norm: "{{ mem_raw | trim | lower | replace(',', '.') | replace('%', '') | replace(' ', '') }}"
            mem_lvl: >-
              {% set v_float = mem_norm | float(default=-1) %}
              {% if v_float < 0 or v_float > 100 %}
                -1
              {% else %}
                {{ v_float }}
              {% endif %}
            mem_display_name: "{{ state_attr(repeat.item, 'friendly_name') or repeat.item }}"

        - if:
            - condition: template
              value_template: "{{ mem_ent not in current_low_entities }}"
          then:
            - if:
                - condition: template
                  value_template: "{{ mem_lvl == -1 }}"
              then:
                - variables:
                    unavailable_memory_entities: "{{ unavailable_memory_entities + [mem_ent] }}"
              else:
                - if:
                    - condition: template
                      value_template: "{{ mem_lvl >= 0 and mem_lvl > threshold + 2 }}"
                  then:
                    - variables:
                        recovered_batteries: "{{ recovered_batteries + [{'name': mem_display_name, 'lvl': mem_lvl}] }}"

  - variables:
      next_memory_entities: "{{ (current_low_entities + unavailable_memory_entities) | unique | list }}"

  - if:
      - condition: template
        value_template: "{{ debug and invalid_entities | length > 0 }}"
    then:
      - service: persistent_notification.create
        data:
          notification_id: "battery_monitor_debug"
          title: "Battery Monitor Debug - Invalid Entities"
          message: >-
            Invalid battery entities (check if *_battery_state was selected by mistake):

            {% for item in invalid_entities %}
            entity_id: {{ item.ent }}
            raw state: {{ item.raw }}
            unit: {{ item.unit }}

            {% endfor %}

  - choose:
      - conditions: "{{ current_low_batteries | length > 0 }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ notify_services_filtered | length > 0 }}"
            then:
              - repeat:
                  for_each: "{{ notify_services_filtered }}"
                  sequence:
                    - service: "{{ repeat.item }}"
                      data:
                        title: "Low Battery Warning"
                        message: >-
                          Devices below {{ threshold }}%:

                          {% for item in current_low_batteries %}
                          - {{ item.name }} ({{ item.lvl | round(0) }}%)
                          {% endfor %}
            else:
              - if:
                  - condition: template
                    value_template: "{{ use_persistent_fallback }}"
                then:
                  - service: persistent_notification.create
                    data:
                      notification_id: "battery_low"
                      title: "Low Battery Warning"
                      message: >-
                        Devices below {{ threshold }}%:

                        {% for item in current_low_batteries %}
                        - {{ item.name }} ({{ item.lvl | round(0) }}%)
                        {% endfor %}

  - choose:
      - conditions: "{{ recovered_batteries | length > 0 }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ notify_services_filtered | length > 0 }}"
            then:
              - repeat:
                  for_each: "{{ notify_services_filtered }}"
                  sequence:
                    - service: "{{ repeat.item }}"
                      data:
                        title: "Battery Recovered"
                        message: >-
                          Devices back above {{ threshold }}%:

                          {% for item in recovered_batteries %}
                          - {{ item.name }} ({{ item.lvl | round(0) }}%)
                          {% endfor %}
            else:
              - if:
                  - condition: template
                    value_template: "{{ use_persistent_fallback }}"
                then:
                  - service: persistent_notification.create
                    data:
                      notification_id: "battery_recovered"
                      title: "Battery Recovered"
                      message: >-
                        Devices back above {{ threshold }}%:

                        {% for item in recovered_batteries %}
                        - {{ item.name }} ({{ item.lvl | round(0) }}%)
                        {% endfor %}

  - service: input_text.set_value
    target:
      entity_id: !input memory_helper
    data:
      value: "{{ next_memory_entities | to_json }}"
