blueprint:
  name: Monitorovanie stavu batérií (opravené v2)
  description: >
    Denne kontroluje vybrané batériové senzory a odosiela notifikácie,
    ak je úroveň pod prahom. Upozornenia sa opakujú, kým sa batéria
    neobnoví (stúpne nad prah). Pamäť je JSON zoznam v input_text.
  domain: automation

  input:
    battery_sensors:
      name: Senzory batérií
      description: Vyberte senzory batérií, ktoré chcete monitorovať
      selector:
        entity:
          domain: sensor
          device_class:
            - battery
          multiple: true

    threshold:
      name: Prah batérie (%)
      default: 15
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1

    notification_time:
      name: Čas notifikácie
      default: "08:00:00"
      selector:
        time: {}

    notification_services:
      name: Notifikačné služby
      description: Každú službu (napr. notify.mobile_app_xyz) na nový riadok.
      default: []
      selector:
        text:
          multiple: true

    use_persistent_fallback:
      name: Persistentný fallback
      description: Ak nie sú zadané notify služby, vytvorí sa persistentná notifikácia v HA.
      default: true
      selector:
        boolean: {}

    memory_helper:
      name: Input text pre pamäť
      description: input_text, kde sa ukladá JSON zoznam už notifikovaných entít.
      selector:
        entity:
          domain: input_text

trigger:
  - platform: time
    at: !input notification_time

variables:
  threshold: !input threshold
  memory_helper: !input memory_helper
  sensors: !input battery_sensors
  notify_services: !input notification_services
  use_persistent_fallback: !input use_persistent_fallback
  memory_list: >-
    {% set raw = states(memory_helper) | string %}
    {% if raw | trim in ['', 'unknown', 'unavailable', 'none'] %}
      []
    {% else %}
      {{ raw | from_json(default=[]) }}
    {% endif %}

mode: single

action:
  - variables:
      low_batteries: []
      recovered_batteries: []
      updated_memory: "{{ memory_list }}"

  - repeat:
      for_each: "{{ sensors }}"
      sequence:
        - variables:
            ent: "{{ repeat.item }}"
            name: "{{ state_attr(repeat.item, 'friendly_name') or repeat.item }}"
            lvl: >-
              {% set v = states(repeat.item) %}
              {% if v is number %}
                {{ v | float }}
              {% elif (v|string|lower) in ['unknown','unavailable','none'] %}
                100
              {% else %}
                {{ v | float(100) }}
              {% endif %}
            was_notified: "{{ ent in updated_memory }}"

        - if:
            - condition: template
              value_template: "{{ lvl < threshold }}"
          then:
            - if:
                - condition: template
                  value_template: "{{ not was_notified }}"
              then:
                - variables:
                    low_batteries: "{{ low_batteries + [name] }}"
                    updated_memory: "{{ updated_memory + [ent] }}"
          else:
            - if:
                - condition: template
                  value_template: "{{ was_notified }}"
              then:
                - variables:
                    recovered_batteries: "{{ recovered_batteries + [name] }}"
                    updated_memory: "{{ updated_memory | reject('equalto', ent) | list }}"

  - choose:
      - conditions: "{{ low_batteries | length > 0 }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ notify_services | length > 0 }}"
            then:
              - repeat:
                  for_each: "{{ notify_services }}"
                  sequence:
                    - service: "{{ repeat.item }}"
                      data:
                        title: "Upozornenie: Nízka batéria"
                        message: >-
                          Zariadenia pod {{ threshold }}%:

                          {% for n in low_batteries %}
                          - {{ n }}
                          {% endfor %}
            else:
              - condition: template
                value_template: "{{ use_persistent_fallback }}"
              - service: persistent_notification.create
                data:
                  title: "Upozornenie: Nízka batéria"
                  message: >-
                    Zariadenia pod {{ threshold }}%:

                    {% for n in low_batteries %}
                    - {{ n }}
                    {% endfor %}

  - choose:
      - conditions: "{{ recovered_batteries | length > 0 }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ notify_services | length > 0 }}"
            then:
              - repeat:
                  for_each: "{{ notify_services }}"
                  sequence:
                    - service: "{{ repeat.item }}"
                      data:
                        title: "Batéria obnovená"
                        message: >-
                          Zariadenia opäť nad {{ threshold }}%:

                          {% for n in recovered_batteries %}
                          - {{ n }}
                          {% endfor %}
            else:
              - condition: template
                value_template: "{{ use_persistent_fallback }}"
              - service: persistent_notification.create
                data:
                  title: "Batéria obnovená"
                  message: >-
                    Zariadenia opäť nad {{ threshold }}%:

                    {% for n in recovered_batteries %}
                    - {{ n }}
                    {% endfor %}

  - service: input_text.set_value
    target:
      entity_id: !input memory_helper
    data:
      value: "{{ updated_memory | to_json }}"
