blueprint:
  name: Sledovanie batérií s denným upozornením a pamäťou
  description: Sleduje batériové entity, upozorňuje pri poklese pod 15 % a posiela denné pripomienky, kým sa batéria nezvýši.
  domain: automation
  input:
    check_time:
      name: Čas upozornenia
      description: Kedy sa má denne kontrolovať stav batérií
      default: "08:00:00"
      selector:
        time: {}
    monitored_batteries:
      name: Sledované batérie
      description: Vyber entity, ktoré chceš sledovať
      selector:
        entity:
          domain: sensor
          multiple: true
    memory_helper:
      name: Pamäť upozornení
      description: input_text pomocník na uchovanie entít, ktoré majú aktívne upozornenie
      selector:
        entity:
          domain: input_text
    notification_service:
      name: Notifikačná služba
      description: Napr. notify.mobile_app_iphone alebo notify.telegram
      default: notify.persistent_notification
      selector:
        text: {}

mode: single

trigger:
  - platform: time
    at: !input check_time

variables:
  notify_service: !input notification_service
  monitored_batteries: !input monitored_batteries
  memory_helper: !input memory_helper
  low_threshold: 15

action:
  - variables:
      notified_entities: >-
        {% set raw = states(memory_helper) %}
        {% if raw and raw != 'unknown' %}
          {{ raw | from_json }}
        {% else %}
          []
        {% endif %}
  - repeat:
      for_each: "{{ monitored_batteries }}"
      sequence:
        - variables:
            battery_entity: "{{ repeat.item }}"
            battery_level: "{{ states(battery_entity) | float(default=100) }}"
        - choose:
            # RESET: Batéria stúpla nad 15 % → odstrániť zo zoznamu
            - conditions:
                - condition: template
                  value_template: "{{ battery_level >= low_threshold and battery_entity in notified_entities }}"
              sequence:
                - service: input_text.set_value
                  data:
                    entity_id: !input memory_helper
                    value: >-
                      {{ (notified_entities | reject('equalto', battery_entity) | list) | to_json }}

            # NOTIFIKÁCIA: Batéria pod 15 % – pošli každý deň, kým sa nezvýši
            - conditions:
                - condition: template
                  value_template: "{{ battery_level < low_threshold }}"
              sequence:
                - service: "{{ notify_service }}"
                  data:
                    title: "🔋 Nízka batéria"
                    message: >
                      Senzor {{ state_attr(battery_entity, 'friendly_name') or battery_entity }}
                      má iba {{ battery_level | int }} % batérie.
                - service: input_text.set_value
                  data:
                    entity_id: !input memory_helper
                    value: >-
                      {{ (notified_entities + [battery_entity]) | unique | to_json }}
