blueprint:
  name: Monitorovanie stavu batérií (opravené v2)
  description: >
    Denne kontroluje vybrané batériové senzory a odosiela notifikácie,
    ak je úroveň pod prahom. Upozornenia sa opakujú, kým sa batéria
    neobnoví (stúpne nad prah). Pamäť je JSON zoznam v input_text.
  domain: automation

  input:
    battery_sensors:
      name: Senzory batérií
      description: Vyberte senzory batérií, ktoré chcete monitorovať
      selector:
        entity:
          multiple: true
          filter:
            - domain: sensor
            - device_class: battery

    threshold:
      name: Prah batérie (%)
      default: 15
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1

    notification_time:
      name: Čas notifikácie
      default: "08:00:00"
      selector:
        time: {}

    notification_services:
      name: Notifikačné služby
      description: Každú službu (napr. notify.mobile_app_xyz) na nový riadok.
      default: []
      selector:
        text:
          multiple: true

    use_persistent_fallback:
      name: Persistentný fallback
      description: Ak nie sú zadané notify služby, vytvorí sa persistentná notifikácia v HA.
      default: true
      selector:
        boolean: {}

    memory_helper:
      name: Input text pre pamäť
      description: input_text, kde sa ukladá JSON zoznam momentálne nízkych batérií z posledného behu.
      selector:
        entity:
          domain: input_text

trigger:
  - platform: time
    at: !input notification_time

variables:
  threshold: !input threshold
  memory_helper: !input memory_helper
  sensors: !input battery_sensors
  notify_services: !input notification_services
  use_persistent_fallback: !input use_persistent_fallback
  memory_list: >-
    {% set raw = states(memory_helper) | string %}
    {% if raw | trim in ['', 'unknown', 'unavailable', 'none'] %}
      []
    {% else %}
      {{ raw | from_json(default=[]) }}
    {% endif %}

mode: single

action:
  - variables:
      current_low_entities: []
      current_low_batteries: []
      recovered_batteries: []

  - repeat:
      for_each: "{{ sensors }}"
      sequence:
        - variables:
            ent: "{{ repeat.item }}"
            state_val: "{{ states(repeat.item) | string }}"
            lvl: >-
              {% set v = states(repeat.item) %}
              {% if v is number %}
                {{ v | float }}
              {% elif (v|string|lower) in ['unknown','unavailable','none'] %}
                null
              {% else %}
                {{ v | float(default=null) }}
              {% endif %}

        - if:
            - condition: template
              value_template: "{{ lvl is not none }}"
          then:
            - variables:
                dev_id: "{{ device_id(repeat.item) }}"
                dev_name: >-
                  {% set d_id = device_id(repeat.item) %}
                  {% if d_id %}
                    {% set d_name = device_attr(d_id, 'name') %}
                    {% if d_name %}
                      {{ d_name }}
                    {% else %}
                      {{ state_attr(repeat.item, 'friendly_name') or repeat.item }}
                    {% endif %}
                  {% else %}
                    {{ state_attr(repeat.item, 'friendly_name') or repeat.item }}
                  {% endif %}
                area: "{{ area_name(repeat.item) }}"
                display_name: >-
                  {% set d_id = device_id(repeat.item) %}
                  {% set d_name = none %}
                  {% if d_id %}
                    {% set d_name = device_attr(d_id, 'name') %}
                  {% endif %}
                  {% if not d_name %}
                    {% set d_name = state_attr(repeat.item, 'friendly_name') or repeat.item %}
                  {% endif %}
                  {% set a = area_name(repeat.item) %}
                  {% if a %}
                    {{ a }} – {{ d_name }}
                  {% else %}
                    {{ d_name }}
                  {% endif %}

            - if:
                - condition: template
                  value_template: "{{ lvl < threshold }}"
              then:
                - variables:
                    current_low_entities: "{{ current_low_entities + [ent] }}"
                    current_low_batteries: "{{ current_low_batteries + [{'name': display_name, 'lvl': lvl}] }}"

  - variables:
      recovered_entities: []

  - repeat:
      for_each: "{{ memory_list }}"
      sequence:
        - if:
            - condition: template
              value_template: "{{ repeat.item not in current_low_entities }}"
          then:
            - variables:
                recovered_entities: "{{ recovered_entities + [repeat.item] }}"

  - repeat:
      for_each: "{{ recovered_entities }}"
      sequence:
        - variables:
            ent: "{{ repeat.item }}"
            state_val: "{{ states(repeat.item) | string }}"
            lvl: >-
              {% set v = states(repeat.item) %}
              {% if v is number %}
                {{ v | float }}
              {% elif (v|string|lower) in ['unknown','unavailable','none'] %}
                null
              {% else %}
                {{ v | float(default=null) }}
              {% endif %}

        - if:
            - condition: template
              value_template: "{{ lvl is not none }}"
          then:
            - variables:
                dev_id: "{{ device_id(repeat.item) }}"
                dev_name: >-
                  {% set d_id = device_id(repeat.item) %}
                  {% if d_id %}
                    {% set d_name = device_attr(d_id, 'name') %}
                    {% if d_name %}
                      {{ d_name }}
                    {% else %}
                      {{ state_attr(repeat.item, 'friendly_name') or repeat.item }}
                    {% endif %}
                  {% else %}
                    {{ state_attr(repeat.item, 'friendly_name') or repeat.item }}
                  {% endif %}
                area: "{{ area_name(repeat.item) }}"
                display_name: >-
                  {% set d_id = device_id(repeat.item) %}
                  {% set d_name = none %}
                  {% if d_id %}
                    {% set d_name = device_attr(d_id, 'name') %}
                  {% endif %}
                  {% if not d_name %}
                    {% set d_name = state_attr(repeat.item, 'friendly_name') or repeat.item %}
                  {% endif %}
                  {% set a = area_name(repeat.item) %}
                  {% if a %}
                    {{ a }} – {{ d_name }}
                  {% else %}
                    {{ d_name }}
                  {% endif %}
            - variables:
                recovered_batteries: "{{ recovered_batteries + [{'name': display_name, 'lvl': lvl}] }}"

  - choose:
      - conditions: "{{ current_low_batteries | length > 0 }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ notify_services | length > 0 }}"
            then:
              - repeat:
                  for_each: "{{ notify_services }}"
                  sequence:
                    - service: "{{ repeat.item }}"
                      data:
                        title: "Upozornenie: Nízka batéria"
                        message: >-
                          Zariadenia pod {{ threshold }}%:

                          {% for item in current_low_batteries %}
                          - {{ item.name }} ({{ item.lvl | round(0) }}%)
                          {% endfor %}
            else:
              - if:
                  - condition: template
                    value_template: "{{ use_persistent_fallback }}"
                then:
                  - service: persistent_notification.create
                    data:
                      title: "Upozornenie: Nízka batéria"
                      message: >-
                        Zariadenia pod {{ threshold }}%:

                        {% for item in current_low_batteries %}
                        - {{ item.name }} ({{ item.lvl | round(0) }}%)
                        {% endfor %}

  - choose:
      - conditions: "{{ recovered_batteries | length > 0 }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ notify_services | length > 0 }}"
            then:
              - repeat:
                  for_each: "{{ notify_services }}"
                  sequence:
                    - service: "{{ repeat.item }}"
                      data:
                        title: "Batéria obnovená"
                        message: >-
                          Zariadenia opäť nad {{ threshold }}%:

                          {% for item in recovered_batteries %}
                          - {{ item.name }} ({{ item.lvl | round(0) }}%)
                          {% endfor %}
            else:
              - if:
                  - condition: template
                    value_template: "{{ use_persistent_fallback }}"
                then:
                  - service: persistent_notification.create
                    data:
                      title: "Batéria obnovená"
                      message: >-
                        Zariadenia opäť nad {{ threshold }}%:

                        {% for item in recovered_batteries %}
                        - {{ item.name }} ({{ item.lvl | round(0) }}%)
                        {% endfor %}

  - service: input_text.set_value
    target:
      entity_id: !input memory_helper
    data:
      value: "{{ current_low_entities | to_json }}"
