blueprint:
  name: Monitorovanie stavu batérií (opravené v3)
  description: >
    Denne kontroluje vybrané batériové senzory a odosiela notifikácie,
    ak je úroveň pod prahom. Upozornenia sa opakujú, kým sa batéria
    neobnoví (stúpne nad prah). Pamäť je JSON zoznam v input_text.
  domain: automation

  input:
    battery_sensors:
      name: Senzory batérií
      description: Vyberte senzory batérií, ktoré chcete monitorovať
      selector:
        entity:
          multiple: true
          filter:
            - domain: sensor
            - device_class: battery

    threshold:
      name: Prah batérie (%)
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1

    notification_time:
      name: Čas notifikácie
      default: "08:00:00"
      selector:
        time: {}

    notification_services:
      name: Notifikačné služby
      description: Každú službu (napr. notify.mobile_app_xyz) na nový riadok.
      default: []
      selector:
        text:
          multiple: true

    use_persistent_fallback:
      name: Persistentný fallback
      description: Ak nie sú zadané notify služby, vytvorí sa persistentná notifikácia v HA.
      default: true
      selector:
        boolean: {}

    memory_helper:
      name: Input text pre pamäť
      description: input_text, kde sa ukladá JSON zoznam momentálne nízkych batérií z posledného behu.
      selector:
        entity:
          domain: input_text

trigger:
  - platform: time
    at: !input notification_time

variables:
  threshold: !input threshold
  memory_helper: !input memory_helper
  sensors: !input battery_sensors
  notify_services: !input notification_services
  notify_services_filtered: >-
    {% set services = notify_services | default([]) %}
    {% set filtered = namespace(list=[]) %}
    {% for svc in services %}
      {% set svc_str = (svc | string | trim) %}
      {% if svc_str and svc_str != '' %}
        {% set _ = filtered.list.append(svc_str) %}
      {% endif %}
    {% endfor %}
    {{ filtered.list }}
  use_persistent_fallback: !input use_persistent_fallback
  memory_list: >-
    {% set raw = states(memory_helper) | string %}
    {% if raw | trim in ['', 'unknown', 'unavailable', 'none'] %}
      []
    {% else %}
      {{ raw | from_json(default=[]) }}
    {% endif %}

mode: single

action:
  - variables:
      current_low_entities: []
      current_low_batteries: []
      recovered_batteries: []
      unavailable_memory_entities: []

  - repeat:
      for_each: "{{ sensors }}"
      sequence:
        - variables:
            ent: "{{ repeat.item }}"
            lvl: >-
              {% set v = states(repeat.item) %}
              {% set v_str = (v | string | trim) | lower %}
              {% if v_str in ['unknown', 'unavailable', 'none', ''] %}
                -1
              {% elif v is number %}
                {% if v >= 0 and v <= 100 %}
                  {{ v | float }}
                {% else %}
                  -1
                {% endif %}
              {% else %}
                {% set v_clean = v_str | regex_replace('[^0-9.]', '') | trim %}
                {% if v_clean and v_clean != '' and v_clean != '.' %}
                  {% set v_float = v_clean | float %}
                  {% if v_float is number and v_float >= 0 and v_float <= 100 %}
                    {{ v_float }}
                  {% else %}
                    -1
                  {% endif %}
                {% else %}
                  -1
                {% endif %}
              {% endif %}
            display_name: >-
              {% set d_id = device_id(repeat.item) %}
              {% set d_name = none %}
              {% if d_id %}
                {% set d_name = device_attr(d_id, 'name') %}
              {% endif %}
              {% if not d_name %}
                {% set d_name = state_attr(repeat.item, 'friendly_name') or repeat.item %}
              {% endif %}
              {% set a = area_name(repeat.item) %}
              {% if a %}
                {{ a }} – {{ d_name }}
              {% else %}
                {{ d_name }}
              {% endif %}

        - if:
            - condition: template
              value_template: "{{ lvl >= 0 and lvl < threshold }}"
          then:
            - variables:
                current_low_entities: "{{ current_low_entities + [ent] }}"
                current_low_batteries: "{{ current_low_batteries + [{'name': display_name, 'lvl': lvl}] }}"

  - repeat:
      for_each: "{{ memory_list }}"
      sequence:
        - variables:
            mem_ent: "{{ repeat.item }}"
            mem_lvl: >-
              {% set v = states(repeat.item) %}
              {% set v_str = (v | string | trim) | lower %}
              {% if v_str in ['unknown', 'unavailable', 'none', ''] %}
                -1
              {% elif v is number %}
                {% if v >= 0 and v <= 100 %}
                  {{ v | float }}
                {% else %}
                  -1
                {% endif %}
              {% else %}
                {% set v_clean = v_str | regex_replace('[^0-9.]', '') | trim %}
                {% if v_clean and v_clean != '' and v_clean != '.' %}
                  {% set v_float = v_clean | float %}
                  {% if v_float is number and v_float >= 0 and v_float <= 100 %}
                    {{ v_float }}
                  {% else %}
                    -1
                  {% endif %}
                {% else %}
                  -1
                {% endif %}
              {% endif %}
            mem_display_name: >-
              {% set d_id = device_id(repeat.item) %}
              {% set d_name = none %}
              {% if d_id %}
                {% set d_name = device_attr(d_id, 'name') %}
              {% endif %}
              {% if not d_name %}
                {% set d_name = state_attr(repeat.item, 'friendly_name') or repeat.item %}
              {% endif %}
              {% set a = area_name(repeat.item) %}
              {% if a %}
                {{ a }} – {{ d_name }}
              {% else %}
                {{ d_name }}
              {% endif %}

        - if:
            - condition: template
              value_template: "{{ mem_ent not in current_low_entities }}"
          then:
            - if:
                - condition: template
                  value_template: "{{ mem_lvl == -1 }}"
              then:
                - variables:
                    unavailable_memory_entities: "{{ unavailable_memory_entities + [mem_ent] }}"
              else:
                - if:
                    - condition: template
                      value_template: "{{ mem_lvl >= 0 and mem_lvl >= threshold }}"
                  then:
                    - variables:
                        recovered_batteries: "{{ recovered_batteries + [{'name': mem_display_name, 'lvl': mem_lvl}] }}"

  - variables:
      next_memory_entities_raw: "{{ current_low_entities + unavailable_memory_entities }}"
      next_memory_entities: >-
        {% set unique_list = namespace(items=[]) %}
        {% for item in next_memory_entities_raw %}
          {% if item not in unique_list.items %}
            {% set _ = unique_list.items.append(item) %}
          {% endif %}
        {% endfor %}
        {{ unique_list.items }}

  - choose:
      - conditions: "{{ current_low_batteries | length > 0 }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ notify_services_filtered | length > 0 }}"
            then:
              - repeat:
                  for_each: "{{ notify_services_filtered }}"
                  sequence:
                    - service: "{{ repeat.item }}"
                      data:
                        title: "Upozornenie: Nízka batéria"
                        message: >-
                          Zariadenia pod {{ threshold }}%:

                          {% for item in current_low_batteries %}
                          - {{ item.name }} ({{ item.lvl | round(0) }}%)
                          {% endfor %}
            else:
              - if:
                  - condition: template
                    value_template: "{{ use_persistent_fallback }}"
                then:
                  - service: persistent_notification.create
                    data:
                      notification_id: "battery_low"
                      title: "Upozornenie: Nízka batéria"
                      message: >-
                        Zariadenia pod {{ threshold }}%:

                        {% for item in current_low_batteries %}
                        - {{ item.name }} ({{ item.lvl | round(0) }}%)
                        {% endfor %}

  - choose:
      - conditions: "{{ recovered_batteries | length > 0 }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ notify_services_filtered | length > 0 }}"
            then:
              - repeat:
                  for_each: "{{ notify_services_filtered }}"
                  sequence:
                    - service: "{{ repeat.item }}"
                      data:
                        title: "Batéria obnovená"
                        message: >-
                          Zariadenia opäť nad {{ threshold }}%:

                          {% for item in recovered_batteries %}
                          - {{ item.name }} ({{ item.lvl | round(0) }}%)
                          {% endfor %}
            else:
              - if:
                  - condition: template
                    value_template: "{{ use_persistent_fallback }}"
                then:
                  - service: persistent_notification.create
                    data:
                      notification_id: "battery_recovered"
                      title: "Batéria obnovená"
                      message: >-
                        Zariadenia opäť nad {{ threshold }}%:

                        {% for item in recovered_batteries %}
                        - {{ item.name }} ({{ item.lvl | round(0) }}%)
                        {% endfor %}

  - service: input_text.set_value
    target:
      entity_id: !input memory_helper
    data:
      value: "{{ next_memory_entities | to_json }}"
