blueprint:
  name: Monitorovanie stavu smart zámkov
  description: >
    Sleduje zmeny stavu zámkov (napr. SwitchBot Lock Pro) a posiela notifikácie pri odomknutí,
    zamknutí, zaseknutí alebo iných stavoch. Podporuje viacero zámkov a notifikačných služieb.
  domain: automation
  input:
    lock_entities:
      name: Zámky
      description: Vyberte zámky, ktoré chcete monitorovať
      selector:
        entity:
          domain: lock
          multiple: true

    notification_services:
      name: Notifikačné služby
      description: Zadajte názvy notifikačných služieb (napr. notify.mobile_app_iphone_jan)
      default: []
      selector:
        text:
          multiple: true

trigger:
  - platform: state
    entity_id: !input lock_entities

condition: []

action:
  - variables:
      lock_entity: "{{ trigger.entity_id }}"
      new_state: "{{ trigger.to_state.state | lower }}"
      lock_name: "{{ state_attr(lock_entity, 'friendly_name') | default(lock_entity) }}"
      lock_location: "{{ area_name(lock_entity) | default(lock_name) }}"
      notification_services: !input notification_services
      message_text: >-
        {% set state_map = {
          'locked': 'bol zamknutý 🔒',
          'unlocked': 'bol odomknutý 🔓',
          'jammed': 'je ZASEKNUTÝ ‼️. Potrebná rekalibrácia!',
          'locking': 'sa práve zamyká ⏳',
          'unlocking': 'sa práve odomyká ⏳',
          'unknown': 'je v neznámom stave ❓'
        } %}
        {% set status = state_map.get(new_state, 'je v stave: ' ~ new_state ~ ' ❓') %}
        {% if lock_name == lock_location %}
          Zámok {{ lock_name }} {{ status }}
        {% else %}
          Zámok {{ lock_name }} v miestnosti {{ lock_location }} {{ status }}
        {% endif %}

  - if:
      - condition: template
        value_template: "{{ notification_services | length > 0 and new_state != 'unknown' }}"
    then:
      - repeat:
          for_each: "{{ notification_services }}"
          sequence:
            - service: "{{ repeat.item }}"
              data:
                title: "🔐 Stav zámku"
                message: "{{ message_text }}"

mode: single
