blueprint:
  name: Hlasové ovládanie zámkov (TTS cez media_player)
  description: >
    Ovládanie smart zámkov cez hlasový príkaz typu "zamkni/odomkni <alias>"
    s výstupným hlásením pomocou TTS na zvolených media_player zariadeniach.
  domain: automation
  input:
    lock_aliases:
      name: Zámky a aliasy
      description: >
        Zoznam názvov, ktoré používateľ vyslovuje (napr. "garáž") a im priradené entity zámkov.
        Príklad: { "garáž": "lock.garazovy_zamok", "predné dvere": "lock.predne_dvere" }
      selector:
        object: {}

    tts_players:
      name: TTS prehrávače
      description: >
        Zariadenia, na ktorých sa má prehrať hlasové potvrdenie.
        (napr. media_player.iphone_jan, media_player.kuchyna)
      selector:
        entity:
          domain: media_player
          multiple: true

    tts_language:
      name: Jazyk TTS
      default: sk
      selector:
        text: {}

    tts_message_template:
      name: Šablóna výstupnej správy
      description: >
        Šablóna hlasovej odpovede. Použi {{ action }} a {{ name }}.
        Napr. "Zámok {{ name }} bol úspešne {{ action }}."
      default: "Zámok {{ name }} bol úspešne {{ action }}."
      selector:
        text: {}

trigger:
  - platform: conversation
    command:
      - zamkni {name}
      - odomkni {name}

variables:
  lock_aliases: !input lock_aliases
  tts_players: !input tts_players
  tts_lang: !input tts_language
  tts_template: !input tts_message_template

  requested_name: "{{ trigger.slots.name | lower }}"
  action_type: >-
    {% if 'zamkni' in trigger.command.lower() %}lock{% elif 'odomkni' in trigger.command.lower() %}unlock{% else %}unknown{% endif %}
  matched_entity: >-
    {% for k, v in lock_aliases.items() %}
      {% if k | lower == requested_name %}
        {{ v }}
      {% endif %}
    {% endfor %}
  matched_alias: >-
    {% for k, v in lock_aliases.items() %}
      {% if k | lower == requested_name %}
        {{ k }}
      {% endif %}
    {% endfor %}
  action_word_sk: >-
    {% if action_type == 'lock' %}zamknutý{% elif action_type == 'unlock' %}odomknutý{% else %}neznámy{% endif %}

action:
  - choose:
      - alias: Ak sa našiel zámok
        conditions:
          - condition: template
            value_template: "{{ matched_entity | length > 0 }}"
        sequence:
          - service: >-
              {% if action_type == 'lock' %}lock.lock
              {% elif action_type == 'unlock' %}lock.unlock
              {% endif %}
            target:
              entity_id: "{{ matched_entity }}"
          - repeat:
              for_each: "{{ tts_players }}"
              sequence:
                - service: tts.speak
                  data:
                    cache: true
                    media_player_entity_id: "{{ repeat.item }}"
                    message: >-
                      {{ tts_template
                        | replace("{{ action }}", action_word_sk)
                        | replace("{{ name }}", matched_alias) }}
                    language: "{{ tts_lang }}"
                  target:
                    entity_id: tts.google_en_com  # použije sa fallback engine

      - alias: Ak sa nenašiel zámok
        conditions:
          - condition: template
            value_template: "{{ matched_entity | length == 0 }}"
        sequence:
          - repeat:
              for_each: "{{ tts_players }}"
              sequence:
                - service: tts.speak
                  data:
                    cache: true
                    media_player_entity_id: "{{ repeat.item }}"
                    message: "Zámok s názvom {{ requested_name }} sa nenašiel."
                    language: "{{ tts_lang }}"
                  target:
                    entity_id: tts.google_en_com

mode: single
