blueprint:
  name: Ovládanie zámkov hlasom (priamy príkaz)
  description: >
    Ovládanie zámkov na základe konkrétnych hlasových príkazov cez Siri / CarPlay.
    Reaguje na presné znenie príkazu (napr. "zamkni garáž") a vykoná akciu + pošle notifikáciu.
  domain: automation
  input:
    command_map:
      name: Príkazy a zámky
      description: >
        Zoznam: príkaz → zámok + akcia.
        Príklad:
          "zamkni garáž": { entity_id: "lock.zamok_garaz", action: "lock" }
          "odomkni garáž": { entity_id: "lock.zamok_garaz", action: "unlock" }
      selector:
        object: {}

    notify_service:
      name: Notifikačná služba
      description: >
        Napr. notify.mobile_app_iphone_jan
      selector:
        text: {}

    notify_template:
      name: Šablóna správy
      description: >
        Použi {{ command }}, {{ entity }}, {{ action }}
      default: "Príkaz '{{ command }}' vykonal akciu '{{ action }}' na zámku {{ entity }}."
      selector:
        text: {}

trigger:
  - platform: conversation
    command:
      - zamkni garáž  # placeholder – reálne príkazy sa mapujú v command_map

variables:
  command_map: !input command_map
  notify_service: !input notify_service
  notify_template: !input notify_template

  received_command: "{{ trigger.command | lower }}"
  matched_entry: "{{ command_map.get(received_command) }}"
  matched_entity: "{{ matched_entry.entity_id if matched_entry is mapping else none }}"
  matched_action: "{{ matched_entry.action if matched_entry is mapping else none }}"

action:
  - choose:
      - alias: Ak sa našiel zámok
        conditions:
          - condition: template
            value_template: "{{ matched_entity is not none and matched_action in ['lock','unlock'] }}"
        sequence:
          - service: "lock.{{ matched_action }}"
            target:
              entity_id: "{{ matched_entity }}"

          - service: "{{ notify_service }}"
            data:
              title: "Zámok ovládaný hlasom"
              message: >-
                {{ notify_template
                  | replace("{{ command }}", received_command)
                  | replace("{{ entity }}", matched_entity)
                  | replace("{{ action }}", matched_action) }}

      - alias: Ak sa nenašiel zámok
        conditions:
          - condition: template
            value_template: "{{ matched_entity is none }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "Zámok neznámy"
              message: "Zámok pre príkaz '{{ received_command }}' sa nenašiel."

mode: single
