blueprint:
  name: Hlasové ovládanie zámkov (notifikácia)
  description: >
    Ovládanie smart zámkov cez hlasový príkaz typu "zamkni/odomkni <alias>"
    s notifikačným potvrdením cez notify službu (napr. notify.mobile_app_iphone).
  domain: automation
  input:
    lock_aliases:
      name: Zámky a aliasy
      description: >
        Zoznam názvov, ktoré používateľ vyslovuje (napr. "garáž") a im priradené entity zámkov.
        Príklad: { "garáž": "lock.garazovy_zamok", "predné dvere": "lock.predne_dvere" }
      selector:
        object: {}

    notify_service:
      name: Notifikačná služba
      description: >
        Vyber službu pre odoslanie notifikácie (napr. notify.mobile_app_iphone_jan).
      selector:
        text: {}

    notify_template:
      name: Text správy
      description: >
        Šablóna textu notifikácie. Použi {{ action }} a {{ name }}.
      default: "Zámok {{ name }} bol úspešne {{ action }}."
      selector:
        text: {}

trigger:
  - platform: conversation
    command:
      - zamkni {name}
      - odomkni {name}

variables:
  lock_aliases: !input lock_aliases
  notify_service: !input notify_service
  notify_template: !input notify_template

  requested_name: "{{ trigger.slots.name | lower }}"
  action_type: >-
    {% if 'zamkni' in trigger.command.lower() %}lock
    {% elif 'odomkni' in trigger.command.lower() %}unlock
    {% else %}unknown{% endif %}
  matched_entity: "{{ lock_aliases.get(requested_name) }}"
  matched_alias: "{{ requested_name }}"
  action_word_sk: >-
    {% if action_type == 'lock' %}zamknutý
    {% elif action_type == 'unlock' %}odomknutý
    {% else %}neznámy{% endif %}

action:
  - choose:
      - alias: Ak sa našiel zámok
        conditions:
          - condition: template
            value_template: "{{ matched_entity is not none }}"
        sequence:
          - service: >-
              {% if action_type == 'lock' %}lock.lock
              {% elif action_type == 'unlock' %}lock.unlock
              {% endif %}
            target:
              entity_id: "{{ matched_entity }}"

          - service: "{{ notify_service }}"
            data:
              title: "Zámok ovládaný hlasom"
              message: >-
                {{ notify_template
                  | replace("{{ action }}", action_word_sk)
                  | replace("{{ name }}", matched_alias) }}

      - alias: Ak sa nenašiel zámok
        conditions:
          - condition: template
            value_template: "{{ matched_entity is none }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "Zámok neidentifikovaný"
              message: "Zámok s názvom {{ requested_name }} sa nenašiel."

mode: single
