blueprint:
  name: Upozornenie na výmenu filtra (HA 2026.1 / memory)
  description: >
    Upozorní, keď je treba vymeniť filter (binary_sensor = on).
    Okamžite pri zmene na on (voliteľné) + denne v čase (kým je stále on).
    Pamäť je JSON zoznam v input_text.

  domain: automation

  input:
    filter_sensors:
      name: Senzory filtra
      description: Binary_sensors, ktoré idú do ON keď treba vymeniť filter.
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    notification_services:
      name: Notifikačné služby
      description: Každú službu (napr. notify.mobile_app_xyz) na nový riadok. Môže byť prázdne.
      default: []
      selector:
        text:
          multiple: true

    use_persistent_fallback:
      name: Persistent fallback
      description: Ak nie sú zadané notify služby, vytvorí sa persistent_notification.
      default: true
      selector:
        boolean: {}

    notification_time:
      name: Čas dennej notifikácie
      default: "08:00:00"
      selector:
        time: {}

    immediate_notification:
      name: Okamžitá notifikácia pri ON
      default: true
      selector:
        boolean: {}

    memory_helper:
      name: Input text pre pamäť
      description: input_text, kde je uložený JSON zoznam senzorov, ktoré boli/ sú aktívne (on).
      selector:
        entity:
          domain: input_text

    title:
      name: Názov notifikácie
      default: "Výmena filtra"
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input filter_sensors
    to: "on"
    id: became_on

  - platform: state
    entity_id: !input filter_sensors
    to: "off"
    id: became_off

  - platform: time
    at: !input notification_time
    id: daily

variables:
  sensor_entities: !input filter_sensors
  notify_services: !input notification_services
  use_persistent: !input use_persistent_fallback
  immediate: !input immediate_notification
  memory_helper: !input memory_helper
  title: !input title

  notify_services_filtered: >-
    {% set services = notify_services | default([]) %}
    {{ services | map('string') | map('trim') | reject('equalto', '') | unique | list }}

  memory_list: >-
    {% set raw = states(memory_helper) | string %}
    {% set t = raw | trim %}
    {% if t in ['', 'unknown', 'unavailable', 'none'] %}
      []
    {% elif t | length >= 2 and t[0] == '[' and t[-1] == ']' %}
      {% set parsed = t | from_json %}
      {% if parsed is list %}
        {{ parsed }}
      {% else %}
        []
      {% endif %}
    {% else %}
      []
    {% endif %}

  active_sensors: >-
    {{ expand(sensor_entities) | selectattr('state', 'eq', 'on') | list }}

  active_entity_ids: >-
    {{ active_sensors | map(attribute='entity_id') | list }}

  message_text: >-
    {% set active = active_sensors %}
    {% if active | length == 1 %}
      {% set s = active[0] %}
      {% set a = area_name(s.entity_id) %}
      {{ (a or 'Neznáma miestnosť') ~ ' – ' ~ s.name ~ ': vymeň filter.' }}
    {% else %}
      Vymeň filter v týchto čističkách:
      {% for s in active %}
        {% set a = area_name(s.entity_id) %}
        - {{ (a or 'Neznáma miestnosť') ~ ' – ' ~ s.name }}
      {% endfor %}
    {% endif %}

mode: queued
max: 10

action:
  # 1) Update memory according to current on/off state
  - variables:
      next_memory: >-
        {% if trigger.id == 'became_off' %}
          {{ memory_list | reject('equalto', trigger.entity_id) | list }}
        {% elif trigger.id == 'became_on' %}
          {{ (memory_list + [trigger.entity_id]) | unique | list }}
        {% else %}
          {{ memory_list }}
        {% endif %}

  - service: input_text.set_value
    target:
      entity_id: !input memory_helper
    data:
      value: "{{ next_memory | to_json }}"

  # 2) Decide whether to notify
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ active_sensors | length > 0 }}"
          - condition: template
            value_template: >
              {{ trigger.id == 'daily' or (trigger.id == 'became_on' and immediate) }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notify_services_filtered | length > 0 }}"
                sequence:
                  - repeat:
                      for_each: "{{ notify_services_filtered }}"
                      sequence:
                        - service: "{{ repeat.item }}"
                          data:
                            title: "{{ title }}"
                            message: "{{ message_text }}"
            default:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ use_persistent }}"
                    sequence:
                      - service: persistent_notification.create
                        data:
                          notification_id: "filter_replace"
                          title: "{{ title }}"
                          message: "{{ message_text }}"
