blueprint:
  name: Upozornenie na výmenu filtra v čističke vzduchu
  description: >
    Upozorňuje používateľa, keď je potrebné vymeniť filter v čističke vzduchu.
    Funguje pre viacero senzorov a notifikačných služieb. Stateless automatizácia.

  domain: automation
  input:
    filter_sensors:
      name: Senzory filtra
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    notification_services:
      name: Notifikačné služby
      default: []
      selector:
        text:
          multiple: true

    notification_time:
      name: Čas dennej notifikácie
      default: "08:00:00"
      selector:
        time: {}

    immediate_notification:
      name: Okamžitá notifikácia
      default: true
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input filter_sensors
    from: "off"
    to: "on"

  - platform: time
    at: !input notification_time

action:
  - variables:
      sensor_entities: !input filter_sensors
      notify_services: !input notification_services
      notify_now: !input immediate_notification

  - variables:
      active_sensors: >
        {% set list = namespace(items=[]) %}
        {% for s in expand(sensor_entities) %}
          {% if s.state == 'on' %}
            {% set list.items = list.items + [s] %}
          {% endif %}
        {% endfor %}
        {{ list.items }}
      message_text: >
        {% if active_sensors | length == 0 %}
          {{ '' }}
        {% elif active_sensors | length == 1 %}
          {% set s = active_sensors[0] %}
          {{ area_name(s.entity_id) | default("Neznáma miestnosť") }} – {{ s.name }}: Vymeň filter!
        {% else %}
          Vymeň filter v týchto čističkách:
          {% for s in active_sensors %}
            • {{ area_name(s.entity_id) | default("Neznáma miestnosť") }} – {{ s.name }}
          {% endfor %}
        {% endif %}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ active_sensors | length > 0 }}"
          - condition: template
            value_template: "{{ notify_services | length > 0 }}"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ trigger.platform == 'time' }}"
              - condition: template
                value_template: "{{ trigger.platform == 'state' and notify_now }}"
        sequence:
          - repeat:
              for_each: "{{ notify_services }}"
              sequence:
                - service: "{{ repeat.item }}"
                  data:
                    title: "Výmena filtra"
                    message: "{{ message_text }}"

mode: queued
max: 10
