blueprint:
  name: Upozornenie na výmenu filtra v čističke vzduchu
  description: >
    Upozornenie na výmenu filtra pre viacero čističiek vzduchu na základe stavu binárnych senzorov.
    Odosiela notifikáciu, ak je aspoň jeden senzor v stave "on", buď okamžite alebo v určený čas.
  domain: automation
  input:
    filter_sensors:
      name: Senzory filtra
      description: Vyberte binárne senzory, ktoré signalizujú potrebu výmeny filtra
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    notification_services:
      name: Notifikačné služby
      description: Zadajte služby na odoslanie (napr. notify.mobile_app_pixel)
      default: []
      selector:
        text:
          multiple: true

    notification_time:
      name: Čas dennej notifikácie
      default: "08:00:00"
      selector:
        time: {}

    immediate_notification:
      name: Okamžitá notifikácia
      default: true
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input filter_sensors
    from: "off"
    to: "on"

  - platform: time
    at: !input notification_time

condition: []

action:
  - variables:
      active_sensors: >
        {% set result = namespace(list=[]) %}
        {% for e in expand(!input filter_sensors) %}
          {% if e.state == 'on' %}
            {% set result.list = result.list + [e] %}
          {% endif %}
        {% endfor %}
        {{ result.list }}

      message_text: >
        {% if active_sensors | count == 0 %}
          {{ '' }}
        {% elif active_sensors | count == 1 %}
          {% set s = active_sensors[0] %}
          {{ area_name(s.entity_id) | default("Neznáma miestnosť") }} – {{ s.name }}: Vymeň filter v čističke vzduchu!
        {% else %}
          Vymeň filter v týchto čističkách:
          {% for s in active_sensors %}
            • {{ area_name(s.entity_id) | default("Neznáma miestnosť") }} – {{ s.name }}
          {% endfor %}
        {% endif %}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ active_sensors | count > 0 }}"
          - condition: template
            value_template: >
              {{ trigger.platform != 'state' or (!input immediate_notification | bool == false and trigger.platform == 'state') == false }}
        sequence:
          - repeat:
              for_each: !input notification_services
              sequence:
                - service: "{{ repeat.item }}"
                  data:
                    title: "Výmena filtra čističky vzduchu"
                    message: "{{ message_text }}"

mode: queued
max: 10
