blueprint:
  name: Upozornenie na výmenu filtra v čističke vzduchu
  description: >
    Automaticky upozorňuje na potrebu výmeny filtra v čističke vzduchu.
    Podporuje viacero senzorov a notifikačných služieb.
    Stateless riešenie bez pamäťovej logiky.

  domain: automation
  input:
    filter_sensors:
      name: Senzory filtra
      description: Vyberte senzory filtra, ktoré chcete monitorovať
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    notification_services:
      name: Notifikačné služby
      description: >
        Zadajte názvy notifikačných služieb (napr. notify.mobile_app_iphone_jan).
        Môžete zadať viacero služieb, každú na nový riadok.
      default: []
      selector:
        text:
          multiple: true

    notification_time:
      name: Čas notifikácie
      description: Kedy sa má notifikácia odosielať (raz denne)
      default: "08:00:00"
      selector:
        time: {}

    immediate_notification:
      name: Okamžitá notifikácia
      description: Poslať notifikáciu okamžite po prepnutí senzora na "on"
      default: true
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input filter_sensors
    from: "off"
    to: "on"

  - platform: time
    at: !input notification_time

action:
  - variables:
      entities: !input filter_sensors
      active_sensors: >
        {{ expand(entities) | selectattr('state', 'eq', 'on') | list }}
      message_text: >
        {% if active_sensors | count == 0 %}
          {{ '' }}
        {% elif active_sensors | count == 1 %}
          {% set s = active_sensors[0] %}
          {% set s_obj = states[s] if s is string else s %}
          {{ area_name(s_obj.entity_id) | default("Neznáma miestnosť") }} – {{ s_obj.attributes.friendly_name | default(s_obj.name) | default(s_obj.entity_id) }}: Vymeň filter v čističke vzduchu!
        {% else %}
          Vymeň filter v týchto čističkách:
          {% for s in active_sensors %}
            {% set s_obj = states[s] if s is string else s %}
            - entity_id: {{ s_obj.entity_id }}, name: {{ s_obj.attributes.friendly_name | default(s_obj.name) | default(s_obj.entity_id) }}, area: {{ area_name(s_obj.entity_id) | default("Neznáma miestnosť") }}
          {% endfor %}
        {% endif %}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ message_text | trim != '' }}"
        sequence:
          - repeat:
              for_each: !input notification_services
              sequence:
                - service: "{{ repeat.item }}"
                  data:
                    title: "Výmena filtra čističky vzduchu"
                    message: "{{ message_text }}"

mode: queued
max: 10
