blueprint:
  name: Upozornenie na výmenu filtra v čističke vzduchu
  description: >
    Automaticky upozorňuje používateľa, keď je potrebné vymeniť filter v čističke vzduchu.
    Podporuje viacero senzorov a viacero notifikačných služieb.
    Pracuje výlučne so stavom 'on' binárnych senzorov, ktoré signalizujú potrebu výmeny filtra.
    Stateless riešenie bez pamäťovej logiky.

  domain: automation
  input:
    filter_sensors:
      name: Senzory filtra
      description: Vyberte senzory filtra, ktoré chcete monitorovať
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    notification_services:
      name: Notifikačné služby
      description: >
        Zadajte názvy notifikačných služieb (napr. notify.mobile_app_pixel).
        Môžete zadať viacero služieb, každú na nový riadok.
      default: []
      selector:
        text:
          multiple: true

    notification_time:
      name: Čas notifikácie
      description: Kedy sa má notifikácia odosielať (raz denne)
      default: "08:00:00"
      selector:
        time: {}

    immediate_notification:
      name: Okamžitá notifikácia
      description: Poslať notifikáciu okamžite po prepnutí senzora na "on"
      default: true
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input filter_sensors
    from: "off"
    to: "on"

  - platform: time
    at: !input notification_time

condition: []

action:
  - variables:
      entities: !input filter_sensors
      notification_services: !input notification_services
      immediate_notification: !input immediate_notification
      active_sensors: >
        {{ expand(entities) | selectattr('state', 'eq', 'on') | list }}
      message_text: >
        {% if active_sensors | count == 0 %}
          {{ '' }}
        {% elif active_sensors | count == 1 %}
          {% set s = active_sensors[0] %}
          {{ area_name(s.entity_id) | default("Neznáma miestnosť") }} – {{ s.attributes.friendly_name | default(s.entity_id) }}: Vymeň filter v čističke vzduchu!
        {% else %}
          Vymeň filter v týchto čističkách:
          {% for s in active_sensors %}
            • {{ area_name(s.entity_id) | default("Neznáma miestnosť") }} – {{ s.attributes.friendly_name | default(s.entity_id) }}
          {% endfor %}
        {% endif %}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ active_sensors | count > 0 }}"
          - condition: template
            value_template: "{{ notification_services | count > 0 }}"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ trigger.platform != 'state' }}"
              - condition: template
                value_template: "{{ (trigger.platform == 'state') and (immediate_notification | bool) }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ message_text | trim != '' }}"
                sequence:
                  - repeat:
                      for_each: "{{ notification_services }}"
                      sequence:
                        - service: "{{ repeat.item }}"
                          data:
                            title: "Výmena filtra čističky vzduchu"
                            message: "{{ message_text }}"

mode: queued
max: 10
