blueprint:
  name: Upozornenie na výmenu filtra (simple / HA 2026.1)
  description: >
    Upozorní keď je binary_sensor "replace_filter" ON.
    - okamžite pri OFF->ON (voliteľné)
    - denne v čase, kým ostáva ON
    - memory_helper ukladá JSON list aktívnych senzorov (entity_id)

  domain: automation

  input:
    filter_sensors:
      name: Senzory filtra (binary_sensor)
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    memory_helper:
      name: Memory helper (input_text)
      description: Musí obsahovať JSON zoznam, napr. []
      selector:
        entity:
          domain: input_text

    notification_services:
      name: Notifikačné služby
      description: Každú službu (napr. notify.mobile_app_xyz) na nový riadok
      default: []
      selector:
        text:
          multiple: true

    use_persistent_fallback:
      name: Persistent fallback
      default: true
      selector:
        boolean: {}

    notification_time:
      name: Čas dennej notifikácie
      default: "08:00:00"
      selector:
        time: {}

    immediate_notification:
      name: Okamžitá notifikácia pri OFF->ON
      default: true
      selector:
        boolean: {}

    title:
      name: Názov notifikácie
      default: "Výmena filtra"
      selector:
        text: {}

    debug:
      name: Debug (persistent)
      default: false
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input filter_sensors
    from: "off"
    to: "on"
    id: became_on

  - platform: time
    at: !input notification_time
    id: daily

mode: queued
max: 10

variables:
  sensors: !input filter_sensors
  memory_helper: !input memory_helper
  notify_services: !input notification_services
  use_persistent: !input use_persistent_fallback
  immediate: !input immediate_notification
  title: !input title
  debug: !input debug

action:
  - variables:
      run_id: >-
        {% if trigger is defined and trigger.id is defined and trigger.id %}
          {{ trigger.id }}
        {% else %}
          manual
        {% endif %}

      notify_services_filtered: >-
        {% set services = notify_services | default([]) %}
        {{ services | map('string') | map('trim') | reject('equalto', '') | unique | list }}

      active_sensors: >-
        {{ expand(sensors) | selectattr('state', 'eq', 'on') | list }}

      active_ids: >-
        {{ active_sensors | map(attribute='entity_id') | list }}

      memory_list: >-
        {% set raw = states(memory_helper) | string | trim %}
        {% if raw in ['', 'unknown', 'unavailable', 'none'] %}
          []
        {% elif raw | length >= 2 and raw[0] == '[' and raw[-1] == ']' %}
          {{ raw | from_json(default=[]) }}
        {% else %}
          []
        {% endif %}

      message_text: >-
        {% if active_sensors | length == 1 %}
          {% set s = active_sensors[0] %}
          {% set a = area_name(s.entity_id) %}
          {{ (a or 'Neznáma miestnosť') ~ ' – ' ~ s.name ~ ': vymeň filter.' }}
        {% else %}
          Vymeň filter v týchto čističkách:
          {% for s in active_sensors %}
            {% set a = area_name(s.entity_id) %}
            - {{ (a or 'Neznáma miestnosť') ~ ' – ' ~ s.name }}
          {% endfor %}
        {% endif %}

      # posielame:
      # - daily/manual: ak je aspoň 1 ON
      # - became_on: len ak immediate=true a entita ešte nebola v memory_list
      should_notify: >-
        {% if run_id in ['daily', 'manual'] %}
          {{ active_sensors | length > 0 }}
        {% elif run_id == 'became_on' %}
          {{ immediate and (trigger.entity_id not in (memory_list | default([]))) }}
        {% else %}
          false
        {% endif %}

      # čo uložiť do helpera
      next_memory: >-
        {{ (active_ids | default([])) }}

  - if:
      - condition: template
        value_template: "{{ debug }}"
    then:
      - service: persistent_notification.create
        data:
          notification_id: "filter_debug"
          title: "Filter Debug"
          message: >-
            run_id={{ run_id }}
            active_ids={{ active_ids }}
            memory_list={{ memory_list }}
            should_notify={{ should_notify }}
            next_memory={{ next_memory }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ should_notify }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notify_services_filtered | length > 0 }}"
                sequence:
                  - repeat:
                      for_each: "{{ notify_services_filtered }}"
                      sequence:
                        - service: "{{ repeat.item }}"
                          data:
                            title: "{{ title }}"
                            message: "{{ message_text }}"
            default:
              - if:
                  - condition: template
                    value_template: "{{ use_persistent }}"
                then:
                  - service: persistent_notification.create
                    data:
                      notification_id: "filter_replace"
                      title: "{{ title }}"
                      message: "{{ message_text }}"

  - service: input_text.set_value
    target:
      entity_id: !input memory_helper
    data:
      value: "{{ next_memory | to_json }}"
