blueprint:
  name: Upozornenie na výmenu filtra v čističke vzduchu
  description: >
    Automaticky upozorňuje na potrebu výmeny filtra v čističke vzduchu.
    Podporuje viacero senzorov a notifikačných služieb.
    Stateless riešenie bez pamäťovej logiky.

  domain: automation
  input:
    filter_sensors:
      name: Senzory filtra
      description: Vyberte senzory filtra, ktoré chcete monitorovať
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    notification_services:
      name: Notifikačné služby
      description: >
        Zadajte názvy notifikačných služieb (napr. notify.mobile_app_iphone_jan).
        Môžete zadať viacero služieb, každú na nový riadok.
      default: []
      selector:
        text:
          multiple: true

    notification_time:
      name: Čas notifikácie
      description: Kedy sa má notifikácia odosielať (raz denne)
      default: "08:00:00"
      selector:
        time: {}

    immediate_notification:
      name: Okamžitá notifikácia
      description: Poslať notifikáciu okamžite po prepnutí senzora na "on"
      default: true
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input filter_sensors
    from: "off"
    to: "on"

  - platform: time
    at: !input notification_time

condition:
  - condition: template
    value_template: >
      {% set active_sensors = filter_sensors | select('is_state', 'on') | list %}
      {{ active_sensors | length > 0 and notification_services | length > 0 }}

  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.platform == 'time' }}"
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ trigger.platform == 'state' }}"
          - condition: template
            value_template: "{{ immediate_notification }}"

action:
  - variables:
      active_sensors: >
        {% set active = filter_sensors | select('is_state', 'on') | list %}
        {{ active }}
      filter_locations: >
        {% set locations = [] %}
        {% for sensor_id in active_sensors %}
          {% set room = area_name(sensor_id) | default('Neznáma miestnosť') %}
          {% set name = state_attr(sensor_id, 'friendly_name') | default(sensor_id) %}
          {% set locations = locations + [room ~ " – " ~ name] %}
        {% endfor %}
        {{ locations }}

  - if:
      - condition: template
        value_template: "{{ filter_locations | length > 0 }}"
    then:
      - repeat:
          for_each: "{{ notification_services }}"
          sequence:
            - service: "{{ repeat.item }}"
              data:
                title: "Výmena filtra čističky vzduchu"
                message: >
                  {% if filter_locations | length == 1 %}
                    {{ filter_locations[0] }}: Vymeň filter v čističke vzduchu!
                  {% else %}
                    Vymeň filter v týchto čističkách: {{ filter_locations | join(', ') }}
                  {% endif %}

mode: queued
max: 10
