blueprint:
  name: Upozornenie na výmenu filtra (stateless / HA 2026.1)
  description: >
    Pošle upozornenie, keď je binary_sensor "replace_filter" ON.
    - okamžite pri OFF->ON (voliteľné)
    - denne v čase, kým ostáva ON
    Bez memory helpera (žiadny limit 255 znakov).

  domain: automation

  input:
    filter_sensors:
      name: Senzory filtra (binary_sensor)
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    notification_services:
      name: Notifikačné služby
      description: Každú službu (napr. notify.mobile_app_xyz) na nový riadok
      default: []
      selector:
        text:
          multiple: true

    use_persistent_fallback:
      name: Persistent fallback
      description: Ak nie sú zadané notify služby, spraví persistent notifikáciu
      default: true
      selector:
        boolean: {}

    notification_time:
      name: Čas dennej notifikácie
      default: "08:00:00"
      selector:
        time: {}

    immediate_notification:
      name: Okamžitá notifikácia pri OFF->ON
      default: true
      selector:
        boolean: {}

    title:
      name: Názov notifikácie
      default: "Výmena filtra"
      selector:
        text: {}

    max_list_items:
      name: Max položiek v správe
      description: Aby správa nebola príliš dlhá
      default: 10
      selector:
        number:
          min: 1
          max: 30
          mode: slider
          step: 1

trigger:
  - platform: state
    entity_id: !input filter_sensors
    from: "off"
    to: "on"
    id: became_on

  - platform: time
    at: !input notification_time
    id: daily

mode: queued
max: 10

variables:
  sensors: !input filter_sensors
  notify_services: !input notification_services
  use_persistent: !input use_persistent_fallback
  immediate: !input immediate_notification
  title: !input title
  max_items: !input max_list_items

action:
  - variables:
      run_id: >-
        {% if trigger is defined and trigger.id is defined and trigger.id %}
          {{ trigger.id }}
        {% else %}
          manual
        {% endif %}

      notify_services_filtered: >-
        {% set services = notify_services | default([]) %}
        {{ services | map('string') | map('trim') | reject('equalto','') | unique | list }}

      active_sensors: >-
        {{ expand(sensors) | selectattr('state','eq','on') | list }}

      should_notify: >-
        {% if run_id in ['daily','manual'] %}
          {{ active_sensors | length > 0 }}
        {% elif run_id == 'became_on' %}
          {{ immediate }}
        {% else %}
          false
        {% endif %}

      message_text: >-
        {% set total = active_sensors | length %}
        {% if total == 0 %}
          {{ '' }}
        {% elif total == 1 %}
          {% set s = active_sensors[0] %}
          {% set a = area_name(s.entity_id) %}
          {{ (a or 'Neznáma miestnosť') ~ ' – ' ~ s.name ~ ': vymeň filter.' }}
        {% else %}
          {% set shown = active_sensors[:max_items] %}
          Vymeň filter v týchto čističkách:
          {% for s in shown %}
            {% set a = area_name(s.entity_id) %}
            - {{ (a or 'Neznáma miestnosť') ~ ' – ' ~ s.name }}
          {% endfor %}
          {% if total > (shown | length) %}
            - … a ďalších {{ total - (shown | length) }}
          {% endif %}
        {% endif %}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ should_notify and (active_sensors | length > 0) }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notify_services_filtered | length > 0 }}"
                sequence:
                  - repeat:
                      for_each: "{{ notify_services_filtered }}"
                      sequence:
                        - service: "{{ repeat.item }}"
                          data:
                            title: "{{ title }}"
                            message: "{{ message_text }}"
            default:
              - if:
                  - condition: template
                    value_template: "{{ use_persistent }}"
                then:
                  - service: persistent_notification.create
                    data:
                      notification_id: "filter_replace"
                      title: "{{ title }}"
                      message: "{{ message_text }}"
