blueprint:
  name: Upozornenie na výmenu filtra v čističke vzduchu
  description: >
    Upozornenie, keď je potrebné vymeniť filter v čističke vzduchu.
    Podporuje viacero senzorov a notifikačných služieb.
    Stateless riešenie.

  domain: automation
  input:
    filter_sensors:
      name: Senzory filtra
      description: Vyberte senzory filtra
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    notification_services:
      name: Notifikačné služby
      description: Napr. notify.mobile_app_pixel
      default: []
      selector:
        text:
          multiple: true

    notification_time:
      name: Čas notifikácie
      default: "08:00:00"
      selector:
        time: {}

    immediate_notification:
      name: Okamžitá notifikácia
      default: true
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input filter_sensors
    from: "off"
    to: "on"
  - platform: time
    at: !input notification_time

variables:
  my_entities: !input filter_sensors
  my_services: !input notification_services
  notify_now: !input immediate_notification

action:
  - variables:
      active_sensors: >
        {% set result = namespace(list=[]) %}
        {% for e in expand(my_entities) %}
          {% if e.state == 'on' %}
            {% set result.list = result.list + [e] %}
          {% endif %}
        {% endfor %}
        {{ result.list }}
      message_text: >
        {% if active_sensors | count == 0 %}
          {{ '' }}
        {% elif active_sensors | count == 1 %}
          {% set s = active_sensors[0] %}
          {{ area_name(s.entity_id) | default("Neznáma miestnosť") }} – {{ s.name }}: Vymeň filter!
        {% else %}
          Vymeň filter v týchto čističkách:
          {% for s in active_sensors %}
            • {{ area_name(s.entity_id) | default("Neznáma miestnosť") }} – {{ s.name }}
          {% endfor %}
        {% endif %}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ active_sensors | count > 0 }}"
          - condition: template
            value_template: "{{ my_services | count > 0 }}"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ trigger.platform != 'state' }}"
              - condition: template
                value_template: "{{ trigger.platform == 'state' and notify_now }}"
        sequence:
          - repeat:
              for_each: "{{ my_services }}"
              sequence:
                - service: "{{ repeat.item }}"
                  data:
                    title: "Výmena filtra"
                    message: "{{ message_text }}"

mode: queued
max: 10
