blueprint:
  name: Weather Voice Assistant (Slovak)
  description: "Odpovie na slovenské hlasové otázky typu 'aké je počasie' pomocou dát zo senzora weather.forecast_domov."
  domain: automation
  input:
    voice_entities:
      name: Voice Assist Entities
      description: "Zoznam zariadení, ktoré môžu ohlásiť predpoveď"
      selector:
        entity:
          domain: assist_satellite
          multiple: true

trigger:
  - platform: conversation
    command:
      - aké je počasie
      - ako je vonku
      - aké je počasie vonku
      - aké je vonku počasie
      - aká je predpoveď počasia
      - aké bude počasie
      - aké dnes bude počasie

action:
  - variables:
      condition_mapping: >
        {% set mapping = {
          'sunny': 'slnečno',
          'partlycloudy': 'čiastočne oblačno',
          'cloudy': 'zamračené',
          'rainy': 'daždivo',
          'snowy': 'sneženie',
          'snowy-rainy': 'dážď so snehom',
          'windy': 'veterno',
          'fog': 'hmla',
          'hail': 'krupobitie',
          'lightning': 'búrka',
          'lightning-rainy': 'búrka s dažďom',
          'clear-night': 'jasná noc',
          'partlycloudy-night': 'čiastočne oblačná noc',
          'overcast': 'zamračené',
          'drizzle': 'mrholenie',
          'scattered-showers': 'prehánky',
          'isolated-thunderstorms': 'izolované búrky',
          'thunderstorms': 'búrky',
          'severe-thunderstorms': 'silné búrky',
          'tornado': 'tornádo',
          'hurricane': 'hurikán',
          'tropical-storm': 'tropická búrka',
          'dust': 'prašan',
          'sand': 'piesok',
          'ash': 'popol',
          'sleet': 'ľadovec',
          'blizzard': 'snehová búrka'
        } %}
        {{ mapping }}
      matched_entity: >
        {% set entities = states | selectattr('entity_id', 'search', 'assist_satellite.') | map(attribute='entity_id') | list %}
        {% set matched = entities | select('is_state', 'processing') | list | first %}
        {{ matched }}
      final_message: >
        {% set weather = states('weather.forecast_domov') %}
        {% set forecast = state_attr('weather.forecast_domov', 'forecast') %}
        {% set current_temp = state_attr('weather.forecast_domov', 'temperature') %}
        {% set wind_speed = state_attr('weather.forecast_domov', 'wind_speed') %}
        {% set condition_translated = condition_mapping.get(weather, 'neznáme') %}
        {% set message = 'Aktuálna predpoveď počasia predpokladá, že bude ' ~ condition_translated ~ '. ' %}
        {% if current_temp is not none %}
          {% set message = message ~ 'Aktuálna teplota je ' ~ current_temp ~ ' stupňov. ' %}
        {% endif %}
        {% if wind_speed is not none %}
          {% set message = message ~ 'Rýchlosť vetra je ' ~ wind_speed ~ ' kilometrov za hodinu. ' %}
        {% endif %}
        {% if forecast is not none %}
          {% set now_ts = as_timestamp(now()) %}
          {% set forecast_24h = [] %}
          {% for entry in forecast %}
            {% if entry.datetime is defined and entry.datetime != '' %}
              {% set entry_ts = as_timestamp(as_datetime(entry.datetime)) %}
              {% if entry_ts <= now_ts + 86400 %}
                {% set forecast_24h = forecast_24h + [entry] %}
              {% endif %}
            {% endif %}
          {% endfor %}
          {% if forecast_24h | length > 0 %}
            {% set min_temp = forecast_24h | map(attribute='temperature') | min %}
            {% set max_temp = forecast_24h | map(attribute='temperature') | max %}
            {% set min_entry = forecast_24h | selectattr('temperature', 'eq', min_temp) | first %}
            {% set max_entry = forecast_24h | selectattr('temperature', 'eq', max_temp) | first %}
            {% if min_temp is not none %}
              {% set message = message ~ 'Najnižšia teplota bude ' ~ min_temp ~ ' stupňov. ' %}
              {% if min_entry %}
                {% set formatted = as_datetime(min_entry.datetime).strftime('%d.%m. o %H:%M') %}
                {% set message = message ~ 'Najnižšia teplota sa očakáva ' ~ formatted ~ '. ' %}
              {% endif %}
            {% endif %}
            {% if max_temp is not none %}
              {% set message = message ~ 'Najvyššia teplota bude ' ~ max_temp ~ ' stupňov. ' %}
              {% if max_entry %}
                {% set formatted = as_datetime(max_entry.datetime).strftime('%d.%m. o %H:%M') %}
                {% set message = message ~ 'Najvyššia teplota sa očakáva ' ~ formatted ~ '. ' %}
              {% endif %}
            {% endif %}
            {% set precip_entries = forecast_24h | selectattr('precipitation', 'gt', 0) | list %}
            {% if precip_entries | length > 0 %}
              {% set first = precip_entries | first %}
              {% set last = precip_entries | last %}
              {% set total = precip_entries | sum(attribute='precipitation') | round(1) %}
              {% if first and last %}
                {% set from = as_datetime(first.datetime).strftime('%d.%m. o %H:%M') %}
                {% set to = as_datetime(last.datetime).strftime('%d.%m. o %H:%M') %}
                {% set message = message ~ 'Zrážky sa očakávajú od ' ~ from ~ ' do ' ~ to ~ '. ' %}
              {% endif %}
              {% if total > 0 %}
                {% set message = message ~ 'Celkové množstvo zrážok bude ' ~ total ~ ' milimetrov. ' %}
              {% endif %}
            {% else %}
              {% set message = message ~ 'Žiadne zrážky sa neočakávajú. ' %}
            {% endif %}
          {% endif %}
        {% else %}
          {% set message = message ~ 'Predpoveď počasia nie je momentálne dostupná. ' %}
        {% endif %}
        {{ message }}

  - if: "{{ matched_entity != '' }}"
    then:
      - service: assist_satellite.announce
        target:
          entity_id: "{{ matched_entity }}"
        data:
          message: "{{ final_message }}"

mode: single
