blueprint:
  name: Hlasové ovládanie roliet (SK)
  description: >
    Ovládanie všetkých roliet cez intent script. Očakáva premennú `action` s hodnotou "otvor" alebo "zatvor".
    Automatizácia sa nespustí, ak nie je zadaná akcia alebo nie sú definované žiadne rolety.
  domain: automation
  input:
    covers_map:
      name: Mapa roliet
      description: >
        Zadajte dictionary, kde kľúč je "všetky" a hodnota je zoznam entity_id roliet.
      selector:
        object: {}
    tts_players:
      name: TTS prehrávače
      description: Vyberte prehrávače pre spätnú väzbu.
      default: []
      selector:
        entity:
          domain: media_player
          multiple: true

# Automatizácia nemá trigger – spúšťa sa cez intent_script.
trigger: []

variables:
  action: "{{ action | default('') }}"
  covers_map: !input covers_map
  covers: >-
    {% if 'všetky' in covers_map %}
      {{ covers_map['všetky'] }}
    {% else %}
      []
    {% endif %}
  covers_count: "{{ covers | count }}"
  tts_players: !input tts_players
  matched_entities: >-
    {% set satellites = states.media_player
      | selectattr('attributes.assist_pipeline_state', 'defined')
      | selectattr('attributes.assist_pipeline_state', 'eq', 'processing')
      | map(attribute='entity_id') | list %}
    {% set intersection = tts_players | select('in', satellites) | list %}
    {{ intersection if intersection else tts_players }}
  tts_sentence: >-
    {% if covers_count > 0 and action in ['otvor', 'zatvor'] %}
      Všetky rolety boli {% if action == 'otvor' %}otvorené{% else %}zatvorené{% endif %}.
    {% else %}
      ''
    {% endif %}

condition:
  - condition: template
    value_template: "{{ action in ['otvor', 'zatvor'] and covers_count > 0 }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ action == 'otvor' }}"
        sequence:
          - service: cover.open_cover
            target:
              entity_id: "{{ covers }}"
          - repeat:
              for_each: "{{ matched_entities }}"
              sequence:
                - service: tts.google_translate_say
                  data:
                    entity_id: "{{ repeat.item }}"
                    message: "{{ tts_sentence }}"
      - conditions:
          - condition: template
            value_template: "{{ action == 'zatvor' }}"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: "{{ covers }}"
          - repeat:
              for_each: "{{ matched_entities }}"
              sequence:
                - service: tts.google_translate_say
                  data:
                    entity_id: "{{ repeat.item }}"
                    message: "{{ tts_sentence }}"
    default:
      - repeat:
          for_each: "{{ matched_entities }}"
          sequence:
            - service: tts.google_translate_say
              data:
                entity_id: "{{ repeat.item }}"
                message: "Neznáma lokalita alebo príkaz. Skúste znova."

mode: single
