blueprint:
  name: Hlasové ovládanie roliet (SK)
  description: >
    Ovládanie roliet hlasom cez príkazy ako „zatvor všetky rolety", „otvor všetky rolety"
    alebo „nastav roletu v [miestnosť] na [percentá]".
    Automaticky zistí aktívny Assist Satellite a prehrá TTS odpoveď len na ňom.
  domain: automation

  input:
    covers_map:
      name: Všetky rolety
      description: >
        Zoznam entít roliet, ktoré sa majú ovládať spoločne.
        Príklad:
        všetky:
          - cover.spalna
          - cover.obyvacka
      selector:
        object: {}

    assist_satellites:
      name: Assist Satellites (fallback)
      description: >
        Voliteľné: Assist Satellite entity pre spätnú väzbu, ak žiadny nie je v stave 'processing'.
        Ak nie je zadané, použije sa prvý dostupný.
      default: []
      selector:
        entity:
          domain: assist_satellite
          multiple: true

    cover_voice_map:
      name: Mapovanie miestností na rolety
      description: >
        Mapovanie hlasových názvov miestností na konkrétne rolety.
        Kľúče môžu byť celé frázy v prirodzenom štýle (napr. "v kuchyni", "na terase", "pri okne").
        Pri porovnávaní sa automaticky odstránia bežné predložky na začiatku (v/vo, na, do, z/zo, k/ku, s/so, u, pri, pred, za, pod, nad, od, medzi, oproti, okolo, cez… a pod.), takže nie je nutné riešiť presný tvar.
        Alias môže byť aj vlastný názov (napr. "office janko"), ktorý sa priradí ku konkrétnej rolete (napr. cover.ikea_fyrtur_office_janko).
        Príklady (alias: entita):
        v kuchyni: cover.ikea_fyrtur_kuchyna
        vo vstupnej hale: cover.xxx
        v jankovej kancelárii: cover.ikea_fyrtur_office_janko
        na terase: cover.xxx
        pri okne: cover.xxx
        oproti kúpeľni: cover.xxx
        medzi izbami: cover.xxx
        do obývačky: cover.xxx
        z kuchyne: cover.xxx
        office janko: cover.ikea_fyrtur_office_janko
        jankova kancelaria: cover.ikea_fyrtur_office_janko
        kuchyni: cover.ikea_fyrtur_kuchyna
        spalna: cover.spalna
        Odporúčanie: používaj unikátne aliasy, aby sa neplietli podobné názvy miestností.
      default: {}
      selector:
        object: {}

trigger:
  - platform: conversation
    command:
      - "otvor všetky rolety"
      - "zatvor všetky rolety"
      - "otvor vsetky rolety"
      - "zatvor vsetky rolety"
      - "nastav roletu v {room} na {pos} percent"
      - "nastav roletu v {room} na {pos} %"
      - "nastav roletu {room} na {pos} percent"
      - "nastav roletu {room} na {pos} %"
      - "nastav roletu v {room} na {pos}"
      - "nastav roletu {room} na {pos}"

variables:
  covers_map: !input covers_map
  assist_satellites: !input assist_satellites
  cover_voice_map: !input cover_voice_map
  command_text: "{{ trigger.sentence | default(trigger.text | default('')) | lower }}"
  room_slot: "{{ trigger.slots.room | default('') | string | trim | lower }}"
  pos_slot: "{{ trigger.slots.pos | default('') | string | trim }}"
  matched_entity: >-
    {% set trigger_satellite = none %}
    {% set dev_id = none %}
    {% if trigger.device_id is defined %}
      {% set dev_id = trigger.device_id %}
    {% elif trigger.platform_data is defined %}
      {% if trigger.platform_data is mapping %}
        {% set dev_id = trigger.platform_data.get('device_id') %}
      {% elif trigger.platform_data.device_id is defined %}
        {% set dev_id = trigger.platform_data.device_id %}
      {% endif %}
    {% endif %}
    {% if dev_id %}
      {% set dev_entities = device_entities(dev_id) if dev_id else [] %}
      {% set trigger_satellite = dev_entities | select('search', 'assist_satellite.') | list | first %}
    {% endif %}
    {% if trigger_satellite %}
      {{ trigger_satellite }}
    {% else %}
      {% set processing = states.assist_satellite
        | selectattr('state', 'eq', 'processing')
        | map(attribute='entity_id')
        | list
        | first %}
      {% if processing %}
        {{ processing }}
      {% elif assist_satellites | length > 0 %}
        {{ assist_satellites[0] }}
      {% else %}
        {% set all_satellites = states.assist_satellite | map(attribute='entity_id') | list %}
        {{ all_satellites[0] if all_satellites | length > 0 else '' }}
      {% endif %}
    {% endif %}

action:
  - variables:
      covers_list: >-
        {% if covers_map is mapping %}
          {% if 'všetky' in covers_map and covers_map['všetky'] is list %}
            {{ covers_map['všetky'] }}
          {% elif 'vsetky' in covers_map and covers_map['vsetky'] is list %}
            {{ covers_map['vsetky'] }}
          {% else %}
            []
          {% endif %}
        {% else %}
          []
        {% endif %}
      covers_list_filtered: "{{ covers_list | select('match', '^cover\\.') | list }}"
      covers_count: "{{ covers_list_filtered | length }}"
      covers_csv: "{{ covers_list_filtered | join(', ') }}"
      has_slots: "{{ (trigger.slots is defined and trigger.slots.room is defined and trigger.slots.pos is defined) and (room_slot != '') and (pos_slot != '') }}"
      action_type: >-
        {% if has_slots %}
          set_position
        {% elif 'otvor' in command_text %}
          open_all
        {% elif 'zatvor' in command_text %}
          close_all
        {% else %}
          unknown
        {% endif %}
      pos_value: >-
        {% if pos_slot %}
          {% set pos_clean = pos_slot | replace(' %', '') | replace('%', '') | replace(' percent', '') | replace('percent', '') | trim %}
          {% if pos_clean is match('^\\d+$') %}
            {{ pos_clean | int }}
          {% else %}
            -1
          {% endif %}
        {% else %}
          -1
        {% endif %}
      pos_valid: "{{ (pos_value | int >= 0) and (pos_value | int <= 100) }}"
      room_norm: >-
        {% if room_slot %}
          {% set preps = ['spomedzi ', 'spredo ', 'spred ', 'spodo ', 'spod ', 'predo ', 'pred ', 'podo ', 'pod ', 'nado ', 'nad ', 'cezo ', 'cez ', 'ponad ', 'popod ', 'popri ', 'vo ', 'zo ', 'ku ', 'so ', 'v ', 'z ', 'k ', 's ', 'na ', 'do ', 'od ', 'u ', 'pri ', 'za ', 'medzi ', 'oproti ', 'okolo ', 'po '] %}
          {% set ns = namespace(value=room_slot | trim | lower, original=room_slot | trim | lower) %}
          {% for _ in range(3) %}
            {% for prep in preps %}
              {% if ns.value.startswith(prep) %}
                {% set ns.value = ns.value[prep|length:] | trim %}
              {% endif %}
            {% endfor %}
          {% endfor %}
          {{ ns.value if ns.value != '' else ns.original }}
        {% else %}
          ''
        {% endif %}
      resolved_data: >-
        {% if room_slot %}
          {% set ns = namespace(found_cover='', found_key_original='') %}
          {% if cover_voice_map is mapping %}
            {% set preps = ['spomedzi ', 'spredo ', 'spred ', 'spodo ', 'spod ', 'predo ', 'pred ', 'podo ', 'pod ', 'nado ', 'nad ', 'cezo ', 'cez ', 'ponad ', 'popod ', 'popri ', 'vo ', 'zo ', 'ku ', 'so ', 'v ', 'z ', 'k ', 's ', 'na ', 'do ', 'od ', 'u ', 'pri ', 'za ', 'medzi ', 'oproti ', 'okolo ', 'po '] %}
            {% for key in cover_voice_map.keys() %}
              {% if not ns.found_cover %}
                {% set key_temp = key | trim | lower %}
                {% set key_ns = namespace(value=key_temp, original=key_temp) %}
                {% for _ in range(3) %}
                  {% for prep in preps %}
                    {% if key_ns.value.startswith(prep) %}
                      {% set key_ns.value = key_ns.value[prep|length:] | trim %}
                    {% endif %}
                  {% endfor %}
                {% endfor %}
                {% set key_norm = key_ns.value if key_ns.value != '' else key_ns.original %}
                {% if key_norm == room_norm %}
                  {% set ns.found_cover = cover_voice_map[key] %}
                  {% set ns.found_key_original = key %}
                {% endif %}
              {% endif %}
            {% endfor %}
          {% endif %}
          {% if not ns.found_cover %}
            {% if covers_list_filtered | length > 0 %}
              {% for cover_ent in covers_list_filtered %}
                {% if not ns.found_cover %}
                  {% set area = area_name(cover_ent) %}
                  {% if area %}
                    {% set area_norm = area | trim | lower %}
                    {% if room_norm in area_norm or area_norm in room_norm %}
                      {% set ns.found_cover = cover_ent %}
                    {% endif %}
                  {% endif %}
                {% endif %}
              {% endfor %}
            {% endif %}
          {% endif %}
          {% set cover_part = ns.found_cover | trim %}
          {% set room_part = (ns.found_key_original if ns.found_key_original != '' else room_slot) | trim %}
          {{ cover_part ~ '|||SEP|||' ~ room_part }}
        {% else %}
          {% set room_part = room_slot | trim %}
          {{ '' ~ '|||SEP|||' ~ room_part }}
        {% endif %}
      resolved_cover_raw: >-
        {% set parts = resolved_data | split('|||SEP|||') %}
        {{ (parts[0] | trim) if parts | length > 0 else '' }}
      resolved_room_name: >-
        {% set parts = resolved_data | split('|||SEP|||') %}
        {{ (parts[1] | trim) if parts | length > 1 else (room_slot | trim) }}
      resolved_cover: "{{ resolved_cover_raw if resolved_cover_raw is match('^cover\\.') else '' }}"
      resolved_cover_valid: "{{ resolved_cover_raw != '' and resolved_cover_raw is match('^cover\\.') }}"
      resolved_cover_invalid: "{{ resolved_cover_raw != '' and not (resolved_cover_raw is match('^cover\\.')) }}"
      tts_sentence: >-
        {% if action_type == 'set_position' %}
          {% if not pos_valid %}
            {% if pos_value | int < 0 %}
              Nerozumiem percentám. Zadaj hodnotu 0 až 100 percent.
            {% else %}
              Zadaj hodnotu 0 až 100 percent.
            {% endif %}
          {% elif resolved_cover_invalid %}
            Mapovanie miestností obsahuje neplatnú entitu. Skontroluj cover_voice_map.
          {% elif not resolved_cover %}
            Neviem, ktorú roletu myslíš. Skontroluj mapovanie miestností.
          {% else %}
            Roleta v {{ resolved_room_name }} bola nastavená na {{ pos_value | int }} percent.
          {% endif %}
        {% elif action_type == 'open_all' %}
          {% if covers_count | int > 0 %}
            Všetky rolety boli otvorené.
          {% else %}
            Chýbajú definované rolety. Skontrolujte konfiguráciu.
          {% endif %}
        {% elif action_type == 'close_all' %}
          {% if covers_count | int > 0 %}
            Všetky rolety boli zatvorené.
          {% else %}
            Chýbajú definované rolety. Skontrolujte konfiguráciu.
          {% endif %}
        {% else %}
          Neznámy príkaz. Použite "otvor všetky rolety", "zatvor všetky rolety" alebo "nastav roletu v [miestnosť] na [percentá]".
        {% endif %}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ action_type == 'open_all' and covers_count | int > 0 }}"
        sequence:
          - service: cover.open_cover
            target:
              entity_id: "{{ covers_csv }}"
      - conditions:
          - condition: template
            value_template: "{{ action_type == 'close_all' and covers_count | int > 0 }}"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: "{{ covers_csv }}"
      - conditions:
          - condition: template
            value_template: "{{ action_type == 'set_position' and pos_valid and resolved_cover_valid }}"
        sequence:
          - service: cover.set_cover_position
            target:
              entity_id: "{{ resolved_cover }}"
            data:
              position: "{{ pos_value | int }}"

  - if:
      - condition: template
        value_template: "{{ matched_entity != '' }}"
    then:
      - service: assist_satellite.announce
        target:
          entity_id: "{{ matched_entity }}"
        data:
          message: "{{ tts_sentence }}"

mode: single
