blueprint:
  name: Weather Voice Assistant (Slovak)
  description: "Hlasový asistent oznamujúce slovenskú predpoveď počasia"
  domain: automation
  input:
    voice_entities:
      name: Voice Assist Entities
      description: "Zoznam zariadení, ktoré môžu ohlásiť predpoveď"
      selector:
        entity:
          domain: assist_satellite
          multiple: true

define:
  number_to_words: &number_to_words
    0: "nula"
    1: "jedna"
    2: "dve"
    3: "tri"
    4: "štyri"
    5: "päť"
    6: "šesť"
    7: "sedem"
    8: "osem"
    9: "deväť"
    10: "desať"
    11: "jedenásť"
    12: "dvanásť"
    13: "trinásť"
    14: "štrnásť"
    15: "pätnásť"
    16: "šestnásť"
    17: "sedemnásť"
    18: "osemnásť"
    19: "devätnásť"
    20: "dvadsať"
    21: "dvadsať jedna"
    22: "dvadsať dva"
    23: "dvadsať tri"
    24: "dvadsať štyri"
    25: "dvadsať päť"
    26: "dvadsať šesť"
    27: "dvadsať sedem"
    28: "dvadsať osem"
    29: "dvadsať deväť"
    30: "tridsať"
    31: "tridsať jedna"
    32: "tridsať dva"
    33: "tridsať tri"
    34: "tridsať štyri"
    35: "tridsať päť"
    36: "tridsať šesť"
    37: "tridsať sedem"
    38: "tridsať osem"
    39: "tridsať deväť"
    40: "štyridsať"

trigger:
  - platform: conversation
    command:
      - aké je počasie
      - ako je vonku
      - aké je počasie vonku
      - aké je vonku počasie
      - aká je predpoveď počasia
      - aké bude počasie
      - aké dnes bude počasie

action:
  - variables:
      number_to_words: *number_to_words
      metno: "sensor.met_no_forecast"
      timeseries: "{{ state_attr(metno, 'timeseries') }}"
      current_temp: >
        {% set val = state_attr('weather.forecast_domov', 'temperature') | float(default=0) %}
        {% set int_part = val | int %}
        {% set dec_part = ((val - int_part)*10)|round|int %}
        {{ number_to_words[int_part] }}{% if dec_part > 0 %} celých {{ number_to_words[dec_part] }}{% endif %} stupňov
      wind_speed: >
        {% set val = state_attr('weather.forecast_domov', 'wind_speed') | float(default=0) %}
        {% set int_part = val | int %}
        {% set dec_part = ((val - int_part)*10)|round|int %}
        {{ number_to_words[int_part] }}{% if dec_part > 0 %} celých {{ number_to_words[dec_part] }}{% endif %} kilometrov za hodinu

  - service: assist_satellite.announce
    target:
      entity_id: "{{ states | selectattr('entity_id','search','assist_satellite.') | selectattr('state','eq','processing') | map(attribute='entity_id') | list | first }}"
    data:
      message: >
        Počasie je aktuálne {{ current_temp }}. Rýchlosť vetra je {{ wind_speed }}. Predpoveď bude doplnená.

mode: single
