blueprint:
  name: Weather Voice Assistant (Slovak - autodetect)
  description: >
    Slovenský hlasový asistent počasia (s predikciou zrážok, časom a trvaním),
    ktorý automaticky zistí Assist Satellite v stave 'processing' a odpovie cez neho.
    Nepotrebuje vstupný zoznam entít.
  domain: automation

  input: {}

trigger:
  - platform: conversation
    command:
      - aké je počasie
      - aké bude počasie
      - aká je predpoveď počasia
      - ako je vonku
      - aké je vonku počasie

action:
  - variables:
      number_to_words: >-
        {{ {
          0:'nula', 1:'jedna', 2:'dve', 3:'tri', 4:'štyri', 5:'päť', 6:'šesť', 7:'sedem', 8:'osem', 9:'deväť',
          10:'desať', 11:'jedenásť', 12:'dvanásť', 13:'trinásť', 14:'štrnásť', 15:'pätnásť', 16:'šestnásť',
          17:'sedemnásť', 18:'osemnásť', 19:'devätnásť', 20:'dvadsať', 21:'dvadsať jedna', 22:'dvadsať dva',
          23:'dvadsať tri', 24:'dvadsať štyri', 25:'dvadsať päť', 26:'dvadsať šesť', 27:'dvadsať sedem',
          28:'dvadsať osem', 29:'dvadsať deväť', 30:'tridsať', 31:'tridsať jedna', 32:'tridsať dva',
          33:'tridsať tri', 34:'tridsať štyri', 35:'tridsať päť', 36:'tridsať šesť', 37:'tridsať sedem',
          38:'tridsať osem', 39:'tridsať deväť', 40:'štyridsať', 41:'štyridsať jedna', 42:'štyridsať dva',
          43:'štyridsať tri', 44:'štyridsať štyri', 45:'štyridsať päť', 46:'štyridsať šesť', 47:'štyridsať sedem',
          48:'štyridsať osem', 49:'štyridsať deväť', 50:'päťdesiat', 51:'päťdesiat jedna', 52:'päťdesiat dva',
          53:'päťdesiat tri', 54:'päťdesiat štyri', 55:'päťdesiat päť', 56:'päťdesiat šesť', 57:'päťdesiat sedem',
          58:'päťdesiat osem', 59:'päťdesiat deväť'
        } }}

      hour_ordinal: >-
        {{ {
          0:'nultej', 1:'prvej', 2:'druhej', 3:'tretej', 4:'štvrtej', 5:'piatej', 6:'šiestej', 7:'siedmej',
          8:'osmej', 9:'deviatej', 10:'desiatej', 11:'jedenástej', 12:'dvanástej', 13:'trinástej', 14:'štrnástej',
          15:'pätnástej', 16:'šestnástej', 17:'sedemnástej', 18:'osemnástej', 19:'devätnástej', 20:'dvadsiatej',
          21:'dvadsiatej prvej', 22:'dvadsiatej druhej', 23:'dvadsiatej tretej'
        } }}

      minute_ordinal: >-
        {{ {
          0:'', 1:'prvej minúte', 2:'druhej minúte', 3:'tretej minúte', 4:'štvrtej minúte',
          5:'piatej minúte', 6:'šiestej minúte', 7:'siedmej minúte', 8:'osmej minúte', 9:'deviatej minúte',
          10:'desiatej minúte', 11:'jedenástej minúte', 12:'dvanástej minúte', 13:'trinástej minúte', 14:'štrnástej minúte',
          15:'pätnástej minúte', 16:'šestnástej minúte', 17:'sedemnástej minúte', 18:'osemnástej minúte', 19:'devätnástej minúte',
          20:'dvadsiatej minúte', 21:'dvadsiatej prvej minúte', 22:'dvadsiatej druhej minúte', 23:'dvadsiatej tretej minúte',
          24:'dvadsiatej štvrtej minúte', 25:'dvadsiatej piatej minúte', 26:'dvadsiatej šiestej minúte',
          27:'dvadsiatej siedmej minúte', 28:'dvadsiatej osmej minúte', 29:'dvadsiatej deviatej minúte',
          30:'tridsiatej minúte', 31:'tridsiatej prvej minúte', 32:'tridsiatej druhej minúte', 33:'tridsiatej tretej minúte',
          34:'tridsiatej štvrtej minúte', 35:'tridsiatej piatej minúte', 36:'tridsiatej šiestej minúte',
          37:'tridsiatej siedmej minúte', 38:'tridsiatej osmej minúte', 39:'tridsiatej deviatej minúte',
          40:'štyridsiatej minúte', 41:'štyridsiatej prvej minúte', 42:'štyridsiatej druhej minúte',
          43:'štyridsiatej tretej minúte', 44:'štyridsiatej štvrtej minúte', 45:'štyridsiatej piatej minúte',
          46:'štyridsiatej šiestej minúte', 47:'štyridsiatej siedmej minúte', 48:'štyridsiatej osmej minúte',
          49:'štyridsiatej deviatej minúte', 50:'päťdesiatej minúte', 51:'päťdesiatej prvej minúte',
          52:'päťdesiatej druhej minúte', 53:'päťdesiatej tretej minúte', 54:'päťdesiatej štvrtej minúte',
          55:'päťdesiatej piatej minúte', 56:'päťdesiatej šiestej minúte', 57:'päťdesiatej siedmej minúte',
          58:'päťdesiatej osmej minúte', 59:'päťdesiatej deviatej minúte'
        } }}

      forecast: "{{ state_attr('sensor.met_no_forecast','timeseries') }}"
      current_temp: "{{ state_attr('weather.forecast_domov','temperature') | float }}"
      wind_speed: "{{ state_attr('weather.forecast_domov','wind_speed') | float }}"

      strong_wind_warning: >-
        {% if wind_speed > 30 %} Pozor, očakáva sa silný vietor. {% else %} {% endif %}

      heavy_rain_warning: >-
        {% set rain_vals = forecast[:24] | map(attribute='data.next_1_hours.details.precipitation_amount') | select('defined') | map('float') | list %}
        {% if rain_vals | sum > 10 %} Upozornenie: očakávajú sa intenzívne zrážky. {% else %} {% endif %}

      min_temp_data: >-
        {% set val = forecast[:24] | sort(attribute='data.instant.details.air_temperature') | first %}
        {% set h = val.time[11:13] | int %}
        {% set m = val.time[14:16] | int %}
        {% set t = val['data']['instant']['details']['air_temperature'] %}
        {% set h_word = hour_ordinal.get(h, h | string) %}
        {% set m_word = minute_ordinal.get(m, m | string) if m > 0 else '' %}
        {{ {'temp': t, 'time': 'o ' ~ h_word ~ (' a ' ~ m_word if m > 0 else ' hodine')} }}

      max_temp_data: >-
        {% set val = forecast[:24] | sort(attribute='data.instant.details.air_temperature', reverse=true) | first %}
        {% set h = val.time[11:13] | int %}
        {% set m = val.time[14:16] | int %}
        {% set t = val['data']['instant']['details']['air_temperature'] %}
        {% set h_word = hour_ordinal.get(h, h | string) %}
        {% set m_word = minute_ordinal.get(m, m | string) if m > 0 else '' %}
        {{ {'temp': t, 'time': 'o ' ~ h_word ~ (' a ' ~ m_word if m > 0 else ' hodine')} }}

      precip_text: >-
        {% set rains = forecast[:24] | selectattr('data.next_1_hours.details.precipitation_amount','gt',0) | list %}
        {% if rains | length > 0 %}
          {% set f = rains[0] %}
          {% set total = forecast[:24] | map(attribute='data.next_1_hours.details.precipitation_amount') | select('defined') | map('float') | list | sum %}
          {% set v = total | float %}
          {% set is_neg = v < 0 %}
          {% set abs_v = v | abs %}
          {% set intp = abs_v | int %}
          {% set dec_raw = ((abs_v - intp) * 10) | round | int %}
          {% if dec_raw >= 10 %}
            {% set intp = intp + 1 %}
            {% set decp = 0 %}
          {% else %}
            {% set decp = dec_raw %}
          {% endif %}
          {% set int_word = number_to_words.get(intp, intp | string) %}
          {% set dec_word = number_to_words.get(decp, decp | string) %}
          {% set prefix = 'mínus ' if is_neg else '' %}
          {% set total_words = prefix ~ int_word ~ ' celých ' ~ dec_word %}
          {% set h = f.time[11:13] | int %}
          Očakávané zrážky okolo {{ hour_ordinal.get(h, h | string) }} hodiny budú spolu asi {{ total_words }} milimetrov.
        {% else %}
          Žiadne zrážky sa neočakávajú.
        {% endif %}

      matched_entity: >-
        {% set entities = states | selectattr('entity_id', 'search', 'assist_satellite.') | map(attribute='entity_id') | list %}
        {% set processing = entities | select('is_state', 'processing') | list | first %}
        {{ processing if processing else entities | first }}

      message_text: >-
        {%- set ct = current_temp | float -%}
        {%- set ct_neg = ct < 0 -%}
        {%- set ct_abs = ct | abs -%}
        {%- set ct_int = ct_abs | int -%}
        {%- set ct_dec_raw = ((ct_abs - ct_int) * 10) | round | int -%}
        {%- if ct_dec_raw >= 10 -%}
          {%- set ct_int = ct_int + 1 -%}
          {%- set ct_dec = 0 -%}
        {%- else -%}
          {%- set ct_dec = ct_dec_raw -%}
        {%- endif -%}
        {%- set ct_int_word = number_to_words.get(ct_int, ct_int | string) -%}
        {%- set ct_prefix = 'mínus ' if ct_neg else '' -%}
        {%- set ct_text = ct_prefix ~ ct_int_word -%}
        {%- if ct_dec > 0 -%}
          {%- set ct_dec_word = number_to_words.get(ct_dec, ct_dec | string) -%}
          {%- set ct_text = ct_text ~ ' celých ' ~ ct_dec_word -%}
        {%- endif -%}
        {%- set msg = 'Aktuálna teplota je ' ~ ct_text ~ ' stupňov Celzia. ' -%}

        {%- set ws = wind_speed | float -%}
        {%- set ws_neg = ws < 0 -%}
        {%- set ws_abs = ws | abs -%}
        {%- set ws_int = ws_abs | int -%}
        {%- set ws_dec_raw = ((ws_abs - ws_int) * 10) | round | int -%}
        {%- if ws_dec_raw >= 10 -%}
          {%- set ws_int = ws_int + 1 -%}
          {%- set ws_dec = 0 -%}
        {%- else -%}
          {%- set ws_dec = ws_dec_raw -%}
        {%- endif -%}
        {%- set ws_int_word = number_to_words.get(ws_int, ws_int | string) -%}
        {%- set ws_prefix = 'mínus ' if ws_neg else '' -%}
        {%- set ws_text = ws_prefix ~ ws_int_word -%}
        {%- if ws_dec > 0 -%}
          {%- set ws_dec_word = number_to_words.get(ws_dec, ws_dec | string) -%}
          {%- set ws_text = ws_text ~ ' celých ' ~ ws_dec_word -%}
        {%- endif -%}
        {%- set msg = msg ~ 'Rýchlosť vetra je ' ~ ws_text ~ ' kilometrov za hodinu. ' ~ strong_wind_warning -%}

        {%- set mint = min_temp_data.temp | float -%}
        {%- set mint_neg = mint < 0 -%}
        {%- set mint_abs = mint | abs -%}
        {%- set mint_int = mint_abs | int -%}
        {%- set mint_dec_raw = ((mint_abs - mint_int) * 10) | round | int -%}
        {%- if mint_dec_raw >= 10 -%}
          {%- set mint_int = mint_int + 1 -%}
          {%- set mint_dec = 0 -%}
        {%- else -%}
          {%- set mint_dec = mint_dec_raw -%}
        {%- endif -%}
        {%- set mint_int_word = number_to_words.get(mint_int, mint_int | string) -%}
        {%- set mint_prefix = 'mínus ' if mint_neg else '' -%}
        {%- set mint_text = mint_prefix ~ mint_int_word -%}
        {%- if mint_dec > 0 -%}
          {%- set mint_dec_word = number_to_words.get(mint_dec, mint_dec | string) -%}
          {%- set mint_text = mint_text ~ ' celých ' ~ mint_dec_word -%}
        {%- endif -%}
        {%- set msg = msg ~ 'Najnižšia teplota bude ' ~ mint_text ~ ' stupňov ' ~ min_temp_data.time ~ '. ' -%}

        {%- set maxt = max_temp_data.temp | float -%}
        {%- set maxt_neg = maxt < 0 -%}
        {%- set maxt_abs = maxt | abs -%}
        {%- set maxt_int = maxt_abs | int -%}
        {%- set maxt_dec_raw = ((maxt_abs - maxt_int) * 10) | round | int -%}
        {%- if maxt_dec_raw >= 10 -%}
          {%- set maxt_int = maxt_int + 1 -%}
          {%- set maxt_dec = 0 -%}
        {%- else -%}
          {%- set maxt_dec = maxt_dec_raw -%}
        {%- endif -%}
        {%- set maxt_int_word = number_to_words.get(maxt_int, maxt_int | string) -%}
        {%- set maxt_prefix = 'mínus ' if maxt_neg else '' -%}
        {%- set maxt_text = maxt_prefix ~ maxt_int_word -%}
        {%- if maxt_dec > 0 -%}
          {%- set maxt_dec_word = number_to_words.get(maxt_dec, maxt_dec | string) -%}
          {%- set maxt_text = maxt_text ~ ' celých ' ~ maxt_dec_word -%}
        {%- endif -%}
        {%- set msg = msg ~ 'Najvyššia teplota bude ' ~ maxt_text ~ ' stupňov ' ~ max_temp_data.time ~ '. ' ~ heavy_rain_warning -%}

        {{ msg ~ precip_text }}

  - service: assist_satellite.announce
    target:
      entity_id: "{{ matched_entity }}"
    data:
      message: "{{ message_text }}"

mode: single
