blueprint:
  name: Weather Voice Assistant (Slovak) - REST
  description: "Odpovie na slovenské hlasové otázky o počasí zo senzora sensor.met_no_forecast"
  domain: automation
  input:
    voice_entities:
      name: Voice Assist Entities
      description: "Zoznam zariadení, ktoré môžu ohlásiť predpoveď"
      selector:
        entity:
          domain: assist_satellite
          multiple: true

trigger:
  - platform: conversation
    command:
      - aké je počasie
      - ako je vonku
      - aké je počasie vonku
      - aké je vonku počasie
      - aká je predpoveď počasia
      - aké bude počasie
      - aké dnes bude počasie

action:
  - variables:
      forecast_data: "{{ state_attr('sensor.met_no_forecast', 'timeseries') }}"
      current: "{{ forecast_data[0] if forecast_data is iterable and forecast_data | length > 0 else {} }}"
      current_temp: >
        {% if current.get('data') and current.data.instant.details.air_temperature is defined %}
          {{ current.data.instant.details.air_temperature }}
        {% else %}
          neznáme
        {% endif %}
      wind_speed: >
        {% if current.get('data') and current.data.instant.details.wind_speed is defined %}
          {{ current.data.instant.details.wind_speed }}
        {% else %}
          neznáme
        {% endif %}
      condition_icon: >
        {% if current.get('data') and current.data.next_1_hours is defined %}
          {{ current.data.next_1_hours.summary.symbol_code.replace('_', ' ') }}
        {% else %}
          neznáme
        {% endif %}
      precipitation_amount: >
        {% if current.get('data') and current.data.next_1_hours.details.precipitation_amount is defined %}
          {{ current.data.next_1_hours.details.precipitation_amount }}
        {% else %}
          0
        {% endif %}
      matched_entity: >
        {% set entities = states | selectattr('entity_id', 'search', 'assist_satellite.') | map(attribute='entity_id') | list %}
        {% set matched = entities | select('is_state', 'processing') | list | first %}
        {{ matched if matched else '' }}
      final_message: >
        Aktuálna teplota je {{ current_temp }} stupňov. 
        Rýchlosť vetra je {{ wind_speed }} kilometrov za hodinu. 
        Podľa predpovede bude {{ condition_icon }}. 
        {% if precipitation_amount | float > 0 %}
          Očakávajú sa zrážky s úhrnom približne {{ precipitation_amount }} mm.
        {% else %}
          Žiadne zrážky sa neočakávajú.
        {% endif %}

  - if: "{{ matched_entity != '' }}"
    then:
      - service: assist_satellite.announce
        target:
          entity_id: "{{ matched_entity }}"
        data:
          message: "{{ final_message }}"

mode: single
