blueprint:
  name: Hlasové ovládanie roliet (SK)
  description: >
    Ovládanie všetkých roliet hlasom cez príkazy ako „zatvor všetky rolety“ alebo „otvor všetky rolety“.
    Automaticky zistí aktívny Assist Satellite a prehrá TTS výstup len na ňom.
  domain: automation

  input:
    covers_map:
      name: Všetky rolety
      description: >
        Zoznam entít roliet, ktoré sa majú ovládať spoločne.
        Príklad:
        všetky:
          - cover.spalna
          - cover.obyvacka
      selector:
        object: {}

trigger:
  - platform: conversation
    command:
      - "otvor všetky rolety"
      - "zatvor všetky rolety"
      - "otvor vsetky rolety"
      - "zatvor vsetky rolety"

action:
  - variables:
      command_text: "{{ trigger.text | lower }}"
      action: >-
        {% if 'zatvor' in command_text %}zatvor{% elif 'otvor' in command_text %}otvor{% else %}''{% endif %}

      # Nájde kľúč "všetky" vo covers_map bez ohľadu na diakritiku
      covers: >-
        {% set all_key = covers_map.keys() | select('match', '^v[šs]etk[ayie]*$') | list | first %}
        {% if all_key %}{{ covers_map[all_key] }}{% else %}[]{% endif %}

      covers_count: "{{ covers | count }}"

      # Zistí Assist Satellite s atribútom 'processing'
      matched_entity: >-
        {% set entities = states.media_player | selectattr('attributes.assist_pipeline_state', 'defined') | selectattr('attributes.assist_pipeline_state', 'eq', 'processing') | map(attribute='entity_id') | list %}
        {{ entities[0] if entities|length > 0 else '' }}

      # Správa pre TTS
      tts_sentence: >-
        {% if covers_count > 0 and action in ['otvor', 'zatvor'] %}
          Všetky rolety boli {% if action == 'otvor' %}otvorené{% else %}zatvorené{% endif %}.
        {% else %}
          Neznámy príkaz alebo chýbajúce rolety.
        {% endif %}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ action == 'otvor' and covers_count > 0 }}"
        sequence:
          - service: cover.open_cover
            target:
              entity_id: "{{ covers }}"

      - conditions:
          - condition: template
            value_template: "{{ action == 'zatvor' and covers_count > 0 }}"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: "{{ covers }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ matched_entity != '' }}"
        sequence:
          - service: assist_satellite.announce
            target:
              entity_id: "{{ matched_entity }}"
            data:
              message: "{{ tts_sentence }}"

mode: single
