blueprint:
  name: Weather Voice Assistant (Slovak)
  description: "Odpovie na hlasové otázky typu 'aké je počasie' pomocou REST senzora met.no"
  domain: automation
  input:
    voice_entities:
      name: Voice Assist Entities
      description: "Zariadenia, ktoré môžu ohlásiť predpoveď"
      selector:
        entity:
          domain: assist_satellite
          multiple: true

trigger:
  - platform: conversation
    command:
      - aké je počasie
      - ako je vonku
      - aké je počasie vonku
      - aké je vonku počasie
      - aká je predpoveď počasia
      - aké bude počasie
      - aké dnes bude počasie

action:
  - variables:
      timeseries: "{{ state_attr('sensor.met_no_forecast', 'timeseries') }}"
      current: "{{ timeseries[0] if timeseries is defined and timeseries | length > 0 else {} }}"
      code: "{{ current.data.next_1_hours.summary.symbol_code if current and current.data and current.data.next_1_hours and current.data.next_1_hours.summary else 'unknown' }}"
      temp: "{{ current.data.instant.details.air_temperature if current and current.data and current.data.instant and current.data.instant.details else '?' }}"
      wind: "{{ current.data.instant.details.wind_speed if current and current.data and current.data.instant and current.data.instant.details else '?' }}"
      rain: "{{ current.data.next_1_hours.details.precipitation_amount if current and current.data and current.data.next_1_hours and current.data.next_1_hours.details else 0 }}"
      text: >
        {% set map = {
          "clearsky_day": "jasno",
          "clearsky_night": "jasná noc",
          "fair_day": "polojasno",
          "fair_night": "polojasná noc",
          "partlycloudy_day": "čiastočne oblačno",
          "partlycloudy_night": "čiastočne oblačná noc",
          "cloudy": "zamračené",
          "rain": "dážď",
          "lightrain": "slabý dážď",
          "heavyrain": "silný dážď",
          "snow": "sneženie",
          "fog": "hmla",
          "rainshowers_day": "prehánky",
          "heavyrainshowers_day": "silné prehánky",
          "lightrainshowers_day": "slabé prehánky"
        } %}
        {{ map[code] if code in map else "neznáme" }}
      device: >
        {% set list = states | selectattr('entity_id', 'search', 'assist_satellite.') | map(attribute='entity_id') | list %}
        {% set found = list | select('is_state', 'processing') | list | first %}
        {{ found }}

      forecast: >
        Aktuálne je {{ text }}.
        Teplota je {{ temp }} °C.
        Rýchlosť vetra {{ wind }} km/h.
        {% if rain | float > 0 %}
          Zrážky: približne {{ rain }} mm v najbližšej hodine.
        {% else %}
          Zrážky sa neočakávajú.
        {% endif %}

  - if: "{{ device != '' }}"
    then:
      - service: assist_satellite.announce
        target:
          entity_id: "{{ device }}"
        data:
          message: "{{ forecast }}"

mode: single
