blueprint:
  name: Hlasové ovládanie roliet (SK)
  description: >
    Ovládanie všetkých roliet hlasom cez príkazy ako „zatvor všetky rolety“ alebo „otvor všetky rolety“.
    Automaticky zistí aktívny Assist Satellite a prehrá TTS odpoveď len na ňom.
  domain: automation

  input:
    covers_map:
      name: Všetky rolety
      description: >
        Zoznam entít roliet, ktoré sa majú ovládať spoločne.
        Príklad:
        všetky:
          - cover.spalna
          - cover.obyvacka
      selector:
        object: {}

    tts_players:
      name: TTS prehrávače
      description: Vyberte prehrávače pre spätnú väzbu.
      default: []
      selector:
        entity:
          domain: media_player
          multiple: true

trigger:
  - platform: conversation
    command:
      - "otvor všetky rolety"
      - "zatvor všetky rolety"
      - "otvor vsetky rolety"
      - "zatvor vsetky rolety"

variables:
  covers_map: !input covers_map
  tts_players: !input tts_players

  command_text: "{{ trigger.text | lower }}"
  action: >-
    {% if 'zatvor' in command_text %}zatvor{% elif 'otvor' in command_text %}otvor{% else %}''{% endif %}

  covers: "{{ covers_map['všetky'] if 'všetky' in covers_map else [] }}"

  matched_entity: >-
    {% set entities = states.media_player
      | selectattr('attributes.assist_pipeline_state', 'defined')
      | selectattr('attributes.assist_pipeline_state', 'eq', 'processing')
      | map(attribute='entity_id') | list %}
    {% set intersection = tts_players | select('in', entities) | list %}
    {{ intersection[0] if intersection | length > 0 else (tts_players[0] if tts_players | length > 0 else '') }}

  tts_sentence: >-
    {% set count = covers | count %}
    {% if count > 0 and action in ['otvor', 'zatvor'] %}
      Všetky rolety boli {% if action == 'otvor' %}otvorené{% else %}zatvorené{% endif %}.
    {% else %}
      Neznámy príkaz alebo chýbajúce rolety.
    {% endif %}

condition:
  - condition: template
    value_template: "{{ action in ['otvor', 'zatvor'] and (covers | count) > 0 }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ action == 'otvor' }}"
        sequence:
          - service: cover.open_cover
            target:
              entity_id: "{{ covers }}"
      - conditions:
          - condition: template
            value_template: "{{ action == 'zatvor' }}"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: "{{ covers }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ matched_entity != '' }}"
        sequence:
          - service: assist_satellite.announce
            target:
              entity_id: "{{ matched_entity }}"
            data:
              message: "{{ tts_sentence }}"

mode: single
