blueprint:
  name: Weather Voice Assistant (Slovak - autodetect)
  description: >
    Slovenský hlasový asistent počasia (s predikciou zrážok, časom a trvaním),
    ktorý automaticky zistí Assist Satellite v stave 'processing' a odpovie cez neho.
    Nepotrebuje vstupný zoznam entít.
  domain: automation

  input: {}

trigger:
  - platform: conversation
    command:
      - aké je počasie
      - aké bude počasie
      - aká je predpoveď počasia
      - ako je vonku
      - aké je vonku počasie

action:
  - variables:
      number_to_words: >-
        {{ dict(((i, ["nula","prvej","druhej","tretej","štvrtej","piatej","šiestej","siedmej","osmej","deviatej",
        "desiatej","jedenástej","dvanástej","trinástej","štrnástej","pätnástej","šestnástej","sedemnástej",
        "osemnástej","devätnástej","dvadsiatej","dvadsiatej prvej","dvadsiatej druhej","dvadsiatej tretej"]) [i] if i <= 23 else str(i)) for i in range(60)) }}

      minute_ordinal: >-
        {{ dict(((i, number_to_words[i] ~ ' minúte') for i in range(60))) }}

      hour_ordinal: >-
        {{ dict(((i, number_to_words[i]) for i in range(24))) }}

      condition_mapping: >-
        {{ {
          'clear-night': 'jasná noc', 'cloudy': 'zamračené', 'fog': 'hmlisto', 'hail': 'krupobitie',
          'lightning': 'blesky', 'lightning-rainy': 'búrka s dažďom', 'partlycloudy': 'čiastočne oblačno',
          'partlycloudy-night': 'polooblačná noc', 'pouring': 'lejak', 'rainy': 'daždivo',
          'snowy': 'sneženie', 'snowy-rainy': 'sneh s dažďom', 'sunny': 'slnečno',
          'windy': 'veterno', 'windy-variant': 'vietor', 'exceptional': 'nezvyčajné'
        } }}

      condition_text: >-
        {% set cond = states('weather.forecast_domov') %}
        {{ condition_mapping.get(cond, 'neznáme počasie') }}

      forecast: "{{ state_attr('sensor.met_no_forecast','timeseries') }}"
      current_temp: "{{ state_attr('weather.forecast_domov','temperature') | float }}"
      wind_speed: "{{ state_attr('weather.forecast_domov','wind_speed') | float }}"

      min_temp: >-
        {% set lst = forecast[:24] | map(attribute='data.instant.details.air_temperature') | list %}
        {{ lst | min }}
      max_temp: >-
        {% set lst = forecast[:24] | map(attribute='data.instant.details.air_temperature') | list %}
        {{ lst | max }}

      min_temp_time: >-
        {% set val = forecast[:24] | sort(attribute='data.instant.details.air_temperature') | first %}
        {% set h = val.time[11:13] | int %}
        {% set m = val.time[14:16] | int %}
        {{ 'o ' ~ number_to_words[h] ~ ' hodine' ~ (' a ' ~ minute_ordinal[m] if m > 0 else '') }}

      max_temp_time: >-
        {% set val = forecast[:24] | sort(attribute='data.instant.details.air_temperature', reverse=true) | first %}
        {% set h = val.time[11:13] | int %}
        {% set m = val.time[14:16] | int %}
        {{ 'o ' ~ number_to_words[h] ~ ' hodine' ~ (' a ' ~ minute_ordinal[m] if m > 0 else '') }}

      precip_hours: >-
        {% set rains = forecast[:24] | selectattr('data.next_1_hours.details.precipitation_amount','gt',0) | list %}
        {{ rains }}

      total_precip_text: >-
        {% set val = forecast[:24] | map(attribute='data.next_1_hours.details.precipitation_amount') | select('defined') | map('float') | list | sum | round(1) %}
        {% set intp = val | int %}
        {% set decp = ((val - intp)*10) | round | int %}
        {% if val == 0 %}nula milimetrov
        {% else %}{{ number_to_words[intp] }} celých {{ number_to_words[decp] }} milimetra{% endif %}

      rain_period: >-
        {% if precip_hours | length > 0 %}
          {% set f = precip_hours[0] %}
          {% set l = precip_hours[-1] %}
          {% set fh = f.time[11:13] | int %}
          {% set fm = f.time[14:16] | int %}
          {% set lh = l.time[11:13] | int %}
          {% set lm = l.time[14:16] | int %}
          {% if fh == lh and fm == lm %}
            {{ 'okolo ' ~ number_to_words[fh] ~ ' hodiny' ~ (' a ' ~ minute_ordinal[fm] if fm > 0 else '') }}
          {% else %}
            medzi {{ number_to_words[fh] ~ ' hodiny' ~ (' a ' ~ minute_ordinal[fm] if fm > 0 else '') }} a {{ number_to_words[lh] ~ ' hodiny' ~ (' a ' ~ minute_ordinal[lm] if lm > 0 else '') }}
          {% endif %}
        {% else %}''{% endif %}

      matched_entity: >-
        {% set entities = states | selectattr('entity_id', 'search', 'assist_satellite.') | map(attribute='entity_id') | list %}
        {% set processing = entities | select('is_state', 'processing') | list | first %}
        {{ processing if processing else entities | first }}

      message_text: >-
        {%- set msg = '' %}
        {%- set it = current_temp | int %}
        {%- set dt = ((current_temp - it)*10) | round | int %}
        {%- set msg = msg ~ 'Momentálne je v lokalite domov ' ~ condition_text ~ '. ' %}
        {%- set msg = msg ~ 'Aktuálna teplota je ' ~ number_to_words[it] %}
        {%- if dt > 0 %}{%- set msg = msg ~ ' celých ' ~ number_to_words[dt] %}{%- endif %}
        {%- set msg = msg ~ ' stupňov Celzia. ' %}

        {%- set iw = wind_speed | int %}
        {%- set dw = ((wind_speed - iw)*10) | round | int %}
        {%- set msg = msg ~ 'Rýchlosť vetra je ' ~ number_to_words[iw] %}
        {%- if dw > 0 %}{%- set msg = msg ~ ' celých ' ~ number_to_words[dw] %}{%- endif %}
        {%- set msg = msg ~ ' kilometrov za hodinu. ' %}

        {%- set mit = min_temp | int %}
        {%- set mdt = ((min_temp - mit)*10) | round | int %}
        {%- set msg = msg ~ 'Najnižšia teplota bude ' ~ number_to_words[mit] %}
        {%- if mdt > 0 %}{%- set msg = msg ~ ' celých ' ~ number_to_words[mdt] %}{%- endif %}
        {%- set msg = msg ~ ' stupňov ' ~ min_temp_time ~ '. ' %}

        {%- set mat = max_temp | int %}
        {%- set mdt2 = ((max_temp - mat)*10) | round | int %}
        {%- set msg = msg ~ 'Najvyššia teplota bude ' ~ number_to_words[mat] %}
        {%- if mdt2 > 0 %}{%- set msg = msg ~ ' celých ' ~ number_to_words[mdt2] %}{%- endif %}
        {%- set msg = msg ~ ' stupňov ' ~ max_temp_time ~ '. ' %}

        {%- if precip_hours | length > 0 %}
          {%- set msg = msg ~ 'Očakávané zrážky ' ~ rain_period ~ '. Celkové množstvo je ' ~ total_precip_text ~ '. ' %}
        {%- else %}
          {%- set msg = msg ~ 'Žiadne zrážky sa neočakávajú. ' %}
        {%- endif %}

        {{ msg }}

  - service: assist_satellite.announce
    target:
      entity_id: "{{ matched_entity }}"
    data:
      message: "{{ message_text }}"

mode: single