blueprint:
  name: Weather Voice Assistant (Slovak)
  description: "Odpovie na hlasové otázky typu 'aké je počasie' zo senzora met.no REST"
  domain: automation
  input:
    voice_entities:
      name: Voice Assist Entities
      description: "Zariadenia, ktoré môžu ohlásiť predpoveď"
      selector:
        entity:
          domain: assist_satellite
          multiple: true

trigger:
  - platform: conversation
    command:
      - aké je počasie
      - ako je vonku
      - aké je počasie vonku
      - aké je vonku počasie
      - aká je predpoveď počasia
      - aké bude počasie
      - aké dnes bude počasie

action:
  - variables:
      timeseries: "{{ state_attr('sensor.met_no_forecast', 'timeseries') }}"
      current: "{{ timeseries[0] if timeseries is defined and timeseries | length > 0 else {} }}"
      condition_code: "{{ current['data']['next_1_hours']['summary']['symbol_code'] if current.get('data') and current['data'].get('next_1_hours') else 'unknown' }}"
      temperature: "{{ current['data']['instant']['details']['air_temperature'] if current.get('data') else 'neznáme' }}"
      wind_speed: "{{ current['data']['instant']['details']['wind_speed'] if current.get('data') else 'neznáme' }}"
      precipitation: "{{ current['data']['next_1_hours']['details']['precipitation_amount'] if current.get('data') and current['data'].get('next_1_hours') and current['data']['next_1_hours'].get('details') else 0 }}"
      mapping: {
        "clearsky_day": "jasno",
        "clearsky_night": "jasná noc",
        "fair_day": "polojasno",
        "fair_night": "polojasná noc",
        "partlycloudy_day": "čiastočne oblačno",
        "partlycloudy_night": "čiastočne oblačná noc",
        "cloudy": "zamračené",
        "rain": "dážď",
        "lightrain": "slabý dážď",
        "heavyrain": "silný dážď",
        "snow": "sneženie",
        "fog": "hmla",
        "heavyrainshowers_day": "silné prehánky",
        "rainshowers_day": "prehánky",
        "lightrainshowers_day": "slabé prehánky"
      }
      condition_text: "{{ mapping.get(condition_code, 'neznáme') }}"
      matched_entity: >
        {% set entities = states | selectattr('entity_id', 'search', 'assist_satellite.') | map(attribute='entity_id') | list %}
        {% set matched = entities | select('is_state', 'processing') | list | first %}
        {{ matched }}

      final_message: >
        Aktuálne je {{ condition_text }}.
        Teplota je {{ temperature }} stupňov.
        Rýchlosť vetra je {{ wind_speed }} km/h.
        {% if precipitation | float > 0 %}
          Očakáva sa zrážky približne {{ precipitation }} mm v najbližšej hodine.
        {% else %}
          Žiadne zrážky sa neočakávajú.
        {% endif %}

  - if: "{{ matched_entity != '' }}"
    then:
      - service: assist_satellite.announce
        target:
          entity_id: "{{ matched_entity }}"
        data:
          message: "{{ final_message }}"

mode: single
