blueprint:
  name: Weather Voice Assistant (Slovak) - REST
  description: "Odpovie na slovenské hlasové otázky o počasí zo senzora sensor.met_no_forecast"
  domain: automation
  input:
    voice_entities:
      name: Voice Assist Entities
      description: "Zoznam zariadení, ktoré môžu ohlásiť predpoveď"
      selector:
        entity:
          domain: assist_satellite
          multiple: true

trigger:
  - platform: conversation
    command:
      - aké je počasie
      - ako je vonku
      - aké je počasie vonku
      - aké je vonku počasie
      - aká je predpoveď počasia
      - aké bude počasie
      - aké dnes bude počasie

action:
  - variables:
      forecast_data: "{{ state_attr('sensor.met_no_forecast', 'timeseries') }}"
      now_ts: "{{ now().timestamp() }}"
      forecast_24h: >
        {{ forecast_data | selectattr('time', 'defined') | selectattr('time', 'ne', '') |
           selectattr('time', 'as_timestamp') | selectattr('time', 'as_timestamp') |
           selectattr('time', 'as_timestamp') | selectattr('time', 'as_timestamp') |
           selectattr('time', 'as_timestamp') |
           selectattr('time', 'as_timestamp') | selectattr('time', 'as_timestamp') | list }}
      current: "{{ forecast_data[0] if forecast_data else {} }}"
      current_temp: "{{ current['data']['instant']['details']['air_temperature'] if current else 'neznáme' }}"
      wind_speed: "{{ current['data']['instant']['details']['wind_speed'] if current else 'neznáme' }}"
      condition_icon: "{{ current['data']['next_1_hours']['summary']['symbol_code'] if current['data'].get('next_1_hours') else 'unknown' }}"
      matched_entity: >
        {% set entities = states | selectattr('entity_id', 'search', 'assist_satellite.') | map(attribute='entity_id') | list %}
        {% set matched = entities | select('is_state', 'processing') | list | first %}
        {{ matched if matched else '' }}
      final_message: >
        Aktuálna teplota je {{ current_temp }} stupňov. Rýchlosť vetra je {{ wind_speed }} kilometrov za hodinu.
        {% if condition_icon %}
          Podľa predpovede bude {{ condition_icon.replace('_', ' ') }}.
        {% endif %}
        {% if forecast_data | length > 0 %}
          {% set precip = forecast_data | selectattr('data.next_1_hours.details.precipitation_amount', 'defined') | list %}
          {% if precip | length > 0 %}
            Očakávajú sa zrážky.
          {% else %}
            Žiadne zrážky sa neočakávajú.
          {% endif %}
        {% endif %}

  - if: "{{ matched_entity != '' }}"
    then:
      - service: assist_satellite.announce
        target:
          entity_id: "{{ matched_entity }}"
        data:
          message: "{{ final_message }}"

mode: single
