blueprint:
  name: Weather Voice Assistant (Slovak)
  description: >
    Slovenský hlasový asistent počasia (s predikciou zrážok a výslovnosťou čísel),
    ktorý odpovie iba cez ten Assist Satellite, ktorý práve spracováva príkaz.
  domain: automation

  input:
    voice_entities:
      name: Voice Assist Entities
      description: Zoznam vašich Assist Satellite entít (napr. assist_satellite.kuchyna)
      selector:
        entity:
          domain: assist_satellite
          multiple: true

trigger:
  - platform: conversation
    command:
      - aké je počasie
      - aké bude počasie
      - aká je predpoveď počasia

action:
  - variables:
      number_to_words: >-
        {{ {
          0:'nula',1:'jedna',2:'dve',3:'tri',4:'štyri',5:'päť',
          6:'šesť',7:'sedem',8:'osem',9:'deväť',10:'desať',
          11:'jedenásť',12:'dvanásť',13:'trinásť',14:'štrnásť',15:'pätnásť',
          16:'šestnásť',17:'sedemnásť',18:'osemnásť',19:'devätnásť',20:'dvadsať',
          21:'dvadsať jedna',22:'dvadsať dva',23:'dvadsať tri',24:'dvadsať štyri',
          25:'dvadsať päť',26:'dvadsať šesť',27:'dvadsať sedem',28:'dvadsať osem',
          29:'dvadsať deväť',30:'tridsať',31:'tridsať jedna',32:'tridsať dva',
          33:'tridsať tri',34:'tridsať štyri',35:'tridsať päť',36:'tridsať šesť',
          37:'tridsať sedem',38:'tridsať osem',39:'tridsať deväť',40:'štyridsať',
          41:'štyridsať jedna',42:'štyridsať dva',43:'štyridsať tri',44:'štyridsať štyri',
          45:'štyridsať päť',46:'štyridsať šesť',47:'štyridsať sedem',48:'štyridsať osem',
          49:'štyridsať deväť',50:'päťdesiat',51:'päťdesiat jedna',52:'päťdesiat dva',
          53:'päťdesiat tri',54:'päťdesiat štyri',55:'päťdesiat päť',56:'päťdesiat šesť',
          57:'päťdesiat sedem',58:'päťdesiat osem',59:'päťdesiat deväť'
        } }}

      forecast: "{{ state_attr('sensor.met_no_forecast','timeseries') }}"
      current_temp: "{{ state_attr('weather.forecast_domov','temperature') | float }}"
      wind_speed: "{{ state_attr('weather.forecast_domov','wind_speed') | float }}"

      min_temp: >-
        {% set lst = forecast[:24] | map(attribute='data.instant.details.air_temperature') | list %}
        {{ lst | min }}
      max_temp: >-
        {% set lst = forecast[:24] | map(attribute='data.instant.details.air_temperature') | list %}
        {{ lst | max }}

      precip_hours: >-
        {% set rains = forecast[:24]
           | selectattr('data.next_1_hours.details.precipitation_amount','gt',0)
           | list %}
        {{ rains }}
      total_precip: >-
        {% set vals = forecast[:24]
           | map(attribute='data.next_1_hours.details.precipitation_amount')
           | select('defined') | map('float') | list %}
        {{ vals | sum | round(1) }}

      # ✅ Jediný satelit, ktorý je aktuálne v stave "processing"
	matched_entity: >-
	  {% set found = '' %}
	  {% for ent in voice_entities %}
	   {% if is_state(ent, 'listening') %}
	     {% set found = ent %}
	     {% break %}
	   {% endif %}
	 {% endfor %}
	 {{ found }}


      message_text: >-
        {%- set msg = '' %}
        {%- set it = current_temp | int %}
        {%- set dt = ((current_temp - it)*10) | round | int %}
        {%- set msg = msg ~ 'Aktuálna teplota je ' ~ number_to_words[it] %}
        {%- if dt > 0 %}{%- set msg = msg ~ ' celých ' ~ number_to_words[dt] %}{%- endif %}
        {%- set msg = msg ~ ' stupňov Celzia. ' %}

        {%- set iw = wind_speed | int %}
        {%- set dw = ((wind_speed - iw)*10) | round | int %}
        {%- set msg = msg ~ 'Rýchlosť vetra je ' ~ number_to_words[iw] %}
        {%- if dw > 0 %}{%- set msg = msg ~ ' celých ' ~ number_to_words[dw] %}{%- endif %}
        {%- set msg = msg ~ ' kilometrov za hodinu. ' %}

        {%- set mit = min_temp | int %}
        {%- set mdt = ((min_temp - mit)*10) | round | int %}
        {%- set msg = msg ~ 'Najnižšia teplota bude ' ~ number_to_words[mit] %}
        {%- if mdt > 0 %}{%- set msg = msg ~ ' celých ' ~ number_to_words[mdt] %}{%- endif %}
        {%- set msg = msg ~ ' stupňov. ' %}

        {%- set mat = max_temp | int %}
        {%- set mdt2 = ((max_temp - mat)*10) | round | int %}
        {%- set msg = msg ~ 'Najvyššia teplota bude ' ~ number_to_words[mat] %}
        {%- if mdt2 > 0 %}{%- set msg = msg ~ ' celých ' ~ number_to_words[mdt2] %}{%- endif %}
        {%- set msg = msg ~ ' stupňov. ' %}

        {%- if precip_hours | length > 0 %}
          {%- set msg = msg ~ 'Zrážky sa očakávajú, celkovo ' ~ total_precip ~ ' mm. ' %}
        {%- else %}
          {%- set msg = msg ~ 'Žiadne zrážky sa neočakávajú. ' %}
        {%- endif %}

        {{ msg }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ matched_entity != '' }}"
        sequence:
          - service: assist_satellite.announce
            target:
              entity_id: "{{ matched_entity }}"
            data:
              message: "{{ message_text }}"

mode: single
